// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/common/project.proto (package libops.v1.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Status } from "./types_pb.js";

/**
 * @generated from enum libops.v1.common.PromoteStrategy
 */
export enum PromoteStrategy {
  /**
   * @generated from enum value: PROMOTE_STRATEGY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Promote on git tags
   *
   * @generated from enum value: PROMOTE_STRATEGY_GITHUB_TAG = 1;
   */
  GITHUB_TAG = 1,

  /**
   * Promote on GitHub releases
   *
   * @generated from enum value: PROMOTE_STRATEGY_GITHUB_RELEASE = 2;
   */
  GITHUB_RELEASE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(PromoteStrategy)
proto3.util.setEnumType(PromoteStrategy, "libops.v1.common.PromoteStrategy", [
  { no: 0, name: "PROMOTE_STRATEGY_UNSPECIFIED" },
  { no: 1, name: "PROMOTE_STRATEGY_GITHUB_TAG" },
  { no: 2, name: "PROMOTE_STRATEGY_GITHUB_RELEASE" },
]);

/**
 * ProjectConfig is the organization-facing project configuration
 * Contains only safe, non-sensitive fields
 *
 * @generated from message libops.v1.common.ProjectConfig
 */
export class ProjectConfig extends Message<ProjectConfig> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: string project_name = 3;
   */
  projectName = "";

  /**
   * Auto-create sites for new branches
   *
   * @generated from field: bool create_branch_sites = 4;
   */
  createBranchSites = false;

  /**
   * GCP deployment configuration
   *
   * GCP region (e.g., "us-central1")
   *
   * @generated from field: string region = 5;
   */
  region = "";

  /**
   * GCP zone (e.g., "us-central1-f")
   *
   * @generated from field: string zone = 6;
   */
  zone = "";

  /**
   * GCP machine type (e.g., "e2-standard-2")
   *
   * @generated from field: string machine_type = 7;
   */
  machineType = "";

  /**
   * Disk size in GB
   *
   * @generated from field: int32 disk_size_gb = 8;
   */
  diskSizeGb = 0;

  /**
   * Promotion strategy
   *
   * How to promote code to production
   *
   * @generated from field: libops.v1.common.PromoteStrategy promote = 11;
   */
  promote = PromoteStrategy.UNSPECIFIED;

  /**
   * Status
   *
   * @generated from field: libops.v1.common.Status status = 16;
   */
  status = Status.UNSPECIFIED;

  constructor(data?: PartialMessage<ProjectConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.common.ProjectConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "create_branch_sites", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "region", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "machine_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "disk_size_gb", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "promote", kind: "enum", T: proto3.getEnumType(PromoteStrategy) },
    { no: 16, name: "status", kind: "enum", T: proto3.getEnumType(Status) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectConfig {
    return new ProjectConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectConfig {
    return new ProjectConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectConfig {
    return new ProjectConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectConfig | PlainMessage<ProjectConfig> | undefined, b: ProjectConfig | PlainMessage<ProjectConfig> | undefined): boolean {
    return proto3.util.equals(ProjectConfig, a, b);
  }
}

