// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/common/site.proto (package libops.v1.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Status } from "./types_pb.js";

/**
 * SiteConfig is the organization-facing site configuration
 * Contains only safe, non-sensitive fields
 *
 * @generated from message libops.v1.common.SiteConfig
 */
export class SiteConfig extends Message<SiteConfig> {
  /**
   * Unique site identifier (UUID)
   *
   * @generated from field: string site_id = 1;
   */
  siteId = "";

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 3;
   */
  projectId = "";

  /**
   * "production", "staging", "development"
   *
   * @generated from field: string site_name = 4;
   */
  siteName = "";

  /**
   * GitHub repository configuration
   *
   * GitHub repository URL
   *
   * @generated from field: string github_repository = 5;
   */
  githubRepository = "";

  /**
   * GitHub reference: heads/{branch_name}, tags/{tag_name}, or "release"
   *
   * @generated from field: string github_ref = 6;
   */
  githubRef = "";

  /**
   * Path to docker-compose directory (default: "")
   *
   * @generated from field: string compose_path = 7;
   */
  composePath = "";

  /**
   * Docker compose file name (default: "docker-compose.yml")
   *
   * @generated from field: string compose_file = 8;
   */
  composeFile = "";

  /**
   * Application configuration
   *
   * Port the application listens on (default: 80)
   *
   * @generated from field: int32 port = 9;
   */
  port = 0;

  /**
   * Type of application (default: "generic")
   *
   * @generated from field: string application_type = 10;
   */
  applicationType = "";

  /**
   * Docker compose commands
   *
   * Commands to start containers
   *
   * @generated from field: repeated string up_cmd = 12;
   */
  upCmd: string[] = [];

  /**
   * Commands to run on initial setup
   *
   * @generated from field: repeated string init_cmd = 13;
   */
  initCmd: string[] = [];

  /**
   * Commands to run during rollout
   *
   * @generated from field: repeated string rollout_cmd = 14;
   */
  rolloutCmd: string[] = [];

  /**
   * Overlay volume paths
   *
   * @generated from field: repeated string overlay_volumes = 15;
   */
  overlayVolumes: string[] = [];

  /**
   * GCP deployment configuration
   *
   * OS image (default: "cos-125-19216-104-74")
   *
   * @generated from field: string os = 16;
   */
  os = "";

  /**
   * Whether this is the production instance
   *
   * @generated from field: bool is_production = 17;
   */
  isProduction = false;

  /**
   * Status (organization-visible)
   *
   * @generated from field: libops.v1.common.Status status = 11;
   */
  status = Status.UNSPECIFIED;

  constructor(data?: PartialMessage<SiteConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.common.SiteConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "site_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "github_repository", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "github_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "compose_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "compose_file", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "application_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "up_cmd", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 13, name: "init_cmd", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 14, name: "rollout_cmd", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 15, name: "overlay_volumes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 16, name: "os", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "is_production", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "status", kind: "enum", T: proto3.getEnumType(Status) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SiteConfig {
    return new SiteConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SiteConfig {
    return new SiteConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SiteConfig {
    return new SiteConfig().fromJsonString(jsonString, options);
  }

  static equals(a: SiteConfig | PlainMessage<SiteConfig> | undefined, b: SiteConfig | PlainMessage<SiteConfig> | undefined): boolean {
    return proto3.util.equals(SiteConfig, a, b);
  }
}

