// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/common/site.proto (package libops.v1.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Status } from "./types_pb.js";

/**
 * SiteConfig is the organization-facing site configuration
 * Contains only safe, non-sensitive fields
 *
 * @generated from message libops.v1.common.SiteConfig
 */
export class SiteConfig extends Message<SiteConfig> {
  /**
   * Unique site identifier (UUID)
   *
   * @generated from field: string site_id = 1;
   */
  siteId = "";

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 3;
   */
  projectId = "";

  /**
   * "production", "staging", "development"
   *
   * @generated from field: string site_name = 4;
   */
  siteName = "";

  /**
   * GitHub reference: heads/{branch_name}, tags/{tag_name}, or "release"
   *
   * @generated from field: string github_ref = 5;
   */
  githubRef = "";

  /**
   * Status (organization-visible)
   *
   * @generated from field: libops.v1.common.Status status = 6;
   */
  status = Status.UNSPECIFIED;

  constructor(data?: PartialMessage<SiteConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.common.SiteConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "site_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "github_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(Status) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SiteConfig {
    return new SiteConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SiteConfig {
    return new SiteConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SiteConfig {
    return new SiteConfig().fromJsonString(jsonString, options);
  }

  static equals(a: SiteConfig | PlainMessage<SiteConfig> | undefined, b: SiteConfig | PlainMessage<SiteConfig> | undefined): boolean {
    return proto3.util.equals(SiteConfig, a, b);
  }
}

