// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file libops/v1/admin_account_api.proto (package libops.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminGetAccountByEmailRequest, AdminGetAccountByEmailResponse, CreateAccountRequest, CreateAccountResponse, DeleteAccountRequest, GetAccountRequest, GetAccountResponse, ListAccountProjectsRequest, ListAccountProjectsResponse, ListAccountRepositoriesRequest, ListAccountRepositoriesResponse, ListAccountsRequest, ListAccountsResponse, UpdateAccountRequest, UpdateAccountResponse } from "./admin_account_api_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { Empty } from "../../google/protobuf/empty_pb.js";

/**
 * AdminAccountService manages user accounts (admin only)
 *
 * @generated from service libops.v1.AdminAccountService
 */
export const AdminAccountService = {
  typeName: "libops.v1.AdminAccountService",
  methods: {
    /**
     * Get account information by ID
     *
     * @generated from rpc libops.v1.AdminAccountService.GetAccount
     */
    getAccount: {
      name: "GetAccount",
      I: GetAccountRequest,
      O: GetAccountResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Get account information by email
     *
     * @generated from rpc libops.v1.AdminAccountService.GetAccountByEmail
     */
    getAccountByEmail: {
      name: "GetAccountByEmail",
      I: AdminGetAccountByEmailRequest,
      O: AdminGetAccountByEmailResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Create a new account
     *
     * @generated from rpc libops.v1.AdminAccountService.CreateAccount
     */
    createAccount: {
      name: "CreateAccount",
      I: CreateAccountRequest,
      O: CreateAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update account information
     *
     * @generated from rpc libops.v1.AdminAccountService.UpdateAccount
     */
    updateAccount: {
      name: "UpdateAccount",
      I: UpdateAccountRequest,
      O: UpdateAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an account
     *
     * @generated from rpc libops.v1.AdminAccountService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * List accounts (admin only)
     *
     * @generated from rpc libops.v1.AdminAccountService.ListAccounts
     */
    listAccounts: {
      name: "ListAccounts",
      I: ListAccountsRequest,
      O: ListAccountsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List projects for an account
     *
     * @generated from rpc libops.v1.AdminAccountService.ListAccountProjects
     */
    listAccountProjects: {
      name: "ListAccountProjects",
      I: ListAccountProjectsRequest,
      O: ListAccountProjectsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List repositories for an account
     *
     * @generated from rpc libops.v1.AdminAccountService.ListAccountRepositories
     */
    listAccountRepositories: {
      name: "ListAccountRepositories",
      I: ListAccountRepositoriesRequest,
      O: ListAccountRepositoriesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

