// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file libops/v1/admin_api.proto (package libops.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminCreateOrganizationRequest, AdminCreateOrganizationResponse, AdminCreateProjectRequest, AdminCreateProjectResponse, AdminCreateSiteRequest, AdminCreateSiteResponse, AdminDeleteOrganizationRequest, AdminDeleteProjectRequest, AdminDeleteSiteRequest, AdminGetOrganizationRequest, AdminGetOrganizationResponse, AdminGetProjectRequest, AdminGetProjectResponse, AdminGetSiteRequest, AdminGetSiteResponse, AdminListAllProjectsRequest, AdminListAllProjectsResponse, AdminListAllSitesRequest, AdminListAllSitesResponse, AdminListOrganizationProjectsRequest, AdminListOrganizationProjectsResponse, AdminListOrganizationsRequest, AdminListOrganizationsResponse, AdminListProjectsRequest, AdminListProjectsResponse, AdminListSitesRequest, AdminListSitesResponse, AdminUpdateOrganizationRequest, AdminUpdateOrganizationResponse, AdminUpdateProjectRequest, AdminUpdateProjectResponse, AdminUpdateSiteRequest, AdminUpdateSiteResponse } from "./admin_api_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { Empty } from "../../google/protobuf/empty_pb.js";

/**
 * AdminOrganizationService manages admin-level organization operations with full access
 *
 * @generated from service libops.v1.AdminOrganizationService
 */
export const AdminOrganizationService = {
  typeName: "libops.v1.AdminOrganizationService",
  methods: {
    /**
     * Get organization configuration (admin view - includes sensitive fields)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.GetOrganization
     */
    getOrganization: {
      name: "GetOrganization",
      I: AdminGetOrganizationRequest,
      O: AdminGetOrganizationResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Create a new organization (admin - can set all fields)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.CreateOrganization
     */
    createOrganization: {
      name: "CreateOrganization",
      I: AdminCreateOrganizationRequest,
      O: AdminCreateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update organization metadata (admin - can update all fields)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.UpdateOrganization
     */
    updateOrganization: {
      name: "UpdateOrganization",
      I: AdminUpdateOrganizationRequest,
      O: AdminUpdateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a organization (must have no projects)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.DeleteOrganization
     */
    deleteOrganization: {
      name: "DeleteOrganization",
      I: AdminDeleteOrganizationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * List all organizations (admin view)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.ListOrganizations
     */
    listOrganizations: {
      name: "ListOrganizations",
      I: AdminListOrganizationsRequest,
      O: AdminListOrganizationsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List projects for a organization (admin view)
     *
     * @generated from rpc libops.v1.AdminOrganizationService.ListOrganizationProjects
     */
    listOrganizationProjects: {
      name: "ListOrganizationProjects",
      I: AdminListOrganizationProjectsRequest,
      O: AdminListOrganizationProjectsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

/**
 * AdminSiteService manages admin-level site operations with full access
 *
 * @generated from service libops.v1.AdminSiteService
 */
export const AdminSiteService = {
  typeName: "libops.v1.AdminSiteService",
  methods: {
    /**
     * List sites (admin view)
     *
     * @generated from rpc libops.v1.AdminSiteService.ListSites
     */
    listSites: {
      name: "ListSites",
      I: AdminListSitesRequest,
      O: AdminListSitesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Get site configuration (admin view - includes internal GCP details)
     *
     * @generated from rpc libops.v1.AdminSiteService.GetSite
     */
    getSite: {
      name: "GetSite",
      I: AdminGetSiteRequest,
      O: AdminGetSiteResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Create a new site (admin - can set all fields)
     *
     * @generated from rpc libops.v1.AdminSiteService.CreateSite
     */
    createSite: {
      name: "CreateSite",
      I: AdminCreateSiteRequest,
      O: AdminCreateSiteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update site configuration (admin - can update all fields)
     *
     * @generated from rpc libops.v1.AdminSiteService.UpdateSite
     */
    updateSite: {
      name: "UpdateSite",
      I: AdminUpdateSiteRequest,
      O: AdminUpdateSiteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a site
     *
     * @generated from rpc libops.v1.AdminSiteService.DeleteSite
     */
    deleteSite: {
      name: "DeleteSite",
      I: AdminDeleteSiteRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * List all sites across all organizations/projects (admin only)
     *
     * @generated from rpc libops.v1.AdminSiteService.ListAllSites
     */
    listAllSites: {
      name: "ListAllSites",
      I: AdminListAllSitesRequest,
      O: AdminListAllSitesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

/**
 * AdminProjectService manages admin-level project operations with full access
 *
 * @generated from service libops.v1.AdminProjectService
 */
export const AdminProjectService = {
  typeName: "libops.v1.AdminProjectService",
  methods: {
    /**
     * Get project configuration (admin view - includes sensitive fields)
     *
     * @generated from rpc libops.v1.AdminProjectService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: AdminGetProjectRequest,
      O: AdminGetProjectResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Create a new project (admin - can set all fields)
     *
     * @generated from rpc libops.v1.AdminProjectService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: AdminCreateProjectRequest,
      O: AdminCreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update project configuration (admin - can update all fields)
     *
     * @generated from rpc libops.v1.AdminProjectService.UpdateProject
     */
    updateProject: {
      name: "UpdateProject",
      I: AdminUpdateProjectRequest,
      O: AdminUpdateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a project (must have no sites)
     *
     * @generated from rpc libops.v1.AdminProjectService.DeleteProject
     */
    deleteProject: {
      name: "DeleteProject",
      I: AdminDeleteProjectRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * List projects for a organization (admin view)
     *
     * @generated from rpc libops.v1.AdminProjectService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: AdminListProjectsRequest,
      O: AdminListProjectsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List all projects across all organizations (admin only)
     *
     * @generated from rpc libops.v1.AdminProjectService.ListAllProjects
     */
    listAllProjects: {
      name: "ListAllProjects",
      I: AdminListAllProjectsRequest,
      O: AdminListAllProjectsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

