// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/admin_api.proto (package libops.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { AdminProjectConfig } from "./admin/project_pb.js";
import { FieldMask } from "../../google/protobuf/field_mask_pb.js";
import { AdminFolderConfig } from "./admin/organization_pb.js";
import { AdminSiteConfig } from "./admin/site_pb.js";

/**
 * @generated from message libops.v1.AdminGetProjectRequest
 */
export class AdminGetProjectRequest extends Message<AdminGetProjectRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  constructor(data?: PartialMessage<AdminGetProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetProjectRequest {
    return new AdminGetProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetProjectRequest {
    return new AdminGetProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetProjectRequest {
    return new AdminGetProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetProjectRequest | PlainMessage<AdminGetProjectRequest> | undefined, b: AdminGetProjectRequest | PlainMessage<AdminGetProjectRequest> | undefined): boolean {
    return proto3.util.equals(AdminGetProjectRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminGetProjectResponse
 */
export class AdminGetProjectResponse extends Message<AdminGetProjectResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminProjectConfig project = 1;
   */
  project?: AdminProjectConfig;

  constructor(data?: PartialMessage<AdminGetProjectResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetProjectResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "project", kind: "message", T: AdminProjectConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetProjectResponse {
    return new AdminGetProjectResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetProjectResponse {
    return new AdminGetProjectResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetProjectResponse {
    return new AdminGetProjectResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetProjectResponse | PlainMessage<AdminGetProjectResponse> | undefined, b: AdminGetProjectResponse | PlainMessage<AdminGetProjectResponse> | undefined): boolean {
    return proto3.util.equals(AdminGetProjectResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateProjectRequest
 */
export class AdminCreateProjectRequest extends Message<AdminCreateProjectRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: libops.v1.admin.AdminProjectConfig project = 2;
   */
  project?: AdminProjectConfig;

  constructor(data?: PartialMessage<AdminCreateProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project", kind: "message", T: AdminProjectConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateProjectRequest {
    return new AdminCreateProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateProjectRequest {
    return new AdminCreateProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateProjectRequest {
    return new AdminCreateProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateProjectRequest | PlainMessage<AdminCreateProjectRequest> | undefined, b: AdminCreateProjectRequest | PlainMessage<AdminCreateProjectRequest> | undefined): boolean {
    return proto3.util.equals(AdminCreateProjectRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateProjectResponse
 */
export class AdminCreateProjectResponse extends Message<AdminCreateProjectResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminProjectConfig project = 1;
   */
  project?: AdminProjectConfig;

  constructor(data?: PartialMessage<AdminCreateProjectResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateProjectResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "project", kind: "message", T: AdminProjectConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateProjectResponse {
    return new AdminCreateProjectResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateProjectResponse {
    return new AdminCreateProjectResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateProjectResponse {
    return new AdminCreateProjectResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateProjectResponse | PlainMessage<AdminCreateProjectResponse> | undefined, b: AdminCreateProjectResponse | PlainMessage<AdminCreateProjectResponse> | undefined): boolean {
    return proto3.util.equals(AdminCreateProjectResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateProjectRequest
 */
export class AdminUpdateProjectRequest extends Message<AdminUpdateProjectRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: libops.v1.admin.AdminProjectConfig project = 3;
   */
  project?: AdminProjectConfig;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 4;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<AdminUpdateProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "project", kind: "message", T: AdminProjectConfig },
    { no: 4, name: "update_mask", kind: "message", T: FieldMask },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateProjectRequest {
    return new AdminUpdateProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateProjectRequest {
    return new AdminUpdateProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateProjectRequest {
    return new AdminUpdateProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateProjectRequest | PlainMessage<AdminUpdateProjectRequest> | undefined, b: AdminUpdateProjectRequest | PlainMessage<AdminUpdateProjectRequest> | undefined): boolean {
    return proto3.util.equals(AdminUpdateProjectRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateProjectResponse
 */
export class AdminUpdateProjectResponse extends Message<AdminUpdateProjectResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminProjectConfig project = 1;
   */
  project?: AdminProjectConfig;

  constructor(data?: PartialMessage<AdminUpdateProjectResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateProjectResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "project", kind: "message", T: AdminProjectConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateProjectResponse {
    return new AdminUpdateProjectResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateProjectResponse {
    return new AdminUpdateProjectResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateProjectResponse {
    return new AdminUpdateProjectResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateProjectResponse | PlainMessage<AdminUpdateProjectResponse> | undefined, b: AdminUpdateProjectResponse | PlainMessage<AdminUpdateProjectResponse> | undefined): boolean {
    return proto3.util.equals(AdminUpdateProjectResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminDeleteProjectRequest
 */
export class AdminDeleteProjectRequest extends Message<AdminDeleteProjectRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  constructor(data?: PartialMessage<AdminDeleteProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminDeleteProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDeleteProjectRequest {
    return new AdminDeleteProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDeleteProjectRequest {
    return new AdminDeleteProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDeleteProjectRequest {
    return new AdminDeleteProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDeleteProjectRequest | PlainMessage<AdminDeleteProjectRequest> | undefined, b: AdminDeleteProjectRequest | PlainMessage<AdminDeleteProjectRequest> | undefined): boolean {
    return proto3.util.equals(AdminDeleteProjectRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListProjectsRequest
 */
export class AdminListProjectsRequest extends Message<AdminListProjectsRequest> {
  /**
   * @generated from field: optional string organization_id = 1;
   */
  organizationId?: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken = "";

  constructor(data?: PartialMessage<AdminListProjectsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListProjectsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListProjectsRequest {
    return new AdminListProjectsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListProjectsRequest {
    return new AdminListProjectsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListProjectsRequest {
    return new AdminListProjectsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListProjectsRequest | PlainMessage<AdminListProjectsRequest> | undefined, b: AdminListProjectsRequest | PlainMessage<AdminListProjectsRequest> | undefined): boolean {
    return proto3.util.equals(AdminListProjectsRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListProjectsResponse
 */
export class AdminListProjectsResponse extends Message<AdminListProjectsResponse> {
  /**
   * @generated from field: repeated libops.v1.admin.AdminProjectConfig projects = 1;
   */
  projects: AdminProjectConfig[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListProjectsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListProjectsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "projects", kind: "message", T: AdminProjectConfig, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListProjectsResponse {
    return new AdminListProjectsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListProjectsResponse {
    return new AdminListProjectsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListProjectsResponse {
    return new AdminListProjectsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListProjectsResponse | PlainMessage<AdminListProjectsResponse> | undefined, b: AdminListProjectsResponse | PlainMessage<AdminListProjectsResponse> | undefined): boolean {
    return proto3.util.equals(AdminListProjectsResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListAllProjectsRequest
 */
export class AdminListAllProjectsRequest extends Message<AdminListAllProjectsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  /**
   * e.g., "organization_id=foo" or "billing_account=bar"
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string;

  constructor(data?: PartialMessage<AdminListAllProjectsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListAllProjectsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListAllProjectsRequest {
    return new AdminListAllProjectsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListAllProjectsRequest {
    return new AdminListAllProjectsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListAllProjectsRequest {
    return new AdminListAllProjectsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListAllProjectsRequest | PlainMessage<AdminListAllProjectsRequest> | undefined, b: AdminListAllProjectsRequest | PlainMessage<AdminListAllProjectsRequest> | undefined): boolean {
    return proto3.util.equals(AdminListAllProjectsRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListAllProjectsResponse
 */
export class AdminListAllProjectsResponse extends Message<AdminListAllProjectsResponse> {
  /**
   * @generated from field: repeated libops.v1.admin.AdminProjectConfig projects = 1;
   */
  projects: AdminProjectConfig[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListAllProjectsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListAllProjectsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "projects", kind: "message", T: AdminProjectConfig, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListAllProjectsResponse {
    return new AdminListAllProjectsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListAllProjectsResponse {
    return new AdminListAllProjectsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListAllProjectsResponse {
    return new AdminListAllProjectsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListAllProjectsResponse | PlainMessage<AdminListAllProjectsResponse> | undefined, b: AdminListAllProjectsResponse | PlainMessage<AdminListAllProjectsResponse> | undefined): boolean {
    return proto3.util.equals(AdminListAllProjectsResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminGetOrganizationRequest
 */
export class AdminGetOrganizationRequest extends Message<AdminGetOrganizationRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  constructor(data?: PartialMessage<AdminGetOrganizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetOrganizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetOrganizationRequest {
    return new AdminGetOrganizationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetOrganizationRequest {
    return new AdminGetOrganizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetOrganizationRequest {
    return new AdminGetOrganizationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetOrganizationRequest | PlainMessage<AdminGetOrganizationRequest> | undefined, b: AdminGetOrganizationRequest | PlainMessage<AdminGetOrganizationRequest> | undefined): boolean {
    return proto3.util.equals(AdminGetOrganizationRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminGetOrganizationResponse
 */
export class AdminGetOrganizationResponse extends Message<AdminGetOrganizationResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminFolderConfig folder = 1;
   */
  folder?: AdminFolderConfig;

  constructor(data?: PartialMessage<AdminGetOrganizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetOrganizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "folder", kind: "message", T: AdminFolderConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetOrganizationResponse {
    return new AdminGetOrganizationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetOrganizationResponse {
    return new AdminGetOrganizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetOrganizationResponse {
    return new AdminGetOrganizationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetOrganizationResponse | PlainMessage<AdminGetOrganizationResponse> | undefined, b: AdminGetOrganizationResponse | PlainMessage<AdminGetOrganizationResponse> | undefined): boolean {
    return proto3.util.equals(AdminGetOrganizationResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateOrganizationRequest
 */
export class AdminCreateOrganizationRequest extends Message<AdminCreateOrganizationRequest> {
  /**
   * @generated from field: libops.v1.admin.AdminFolderConfig folder = 1;
   */
  folder?: AdminFolderConfig;

  constructor(data?: PartialMessage<AdminCreateOrganizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateOrganizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "folder", kind: "message", T: AdminFolderConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateOrganizationRequest {
    return new AdminCreateOrganizationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateOrganizationRequest {
    return new AdminCreateOrganizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateOrganizationRequest {
    return new AdminCreateOrganizationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateOrganizationRequest | PlainMessage<AdminCreateOrganizationRequest> | undefined, b: AdminCreateOrganizationRequest | PlainMessage<AdminCreateOrganizationRequest> | undefined): boolean {
    return proto3.util.equals(AdminCreateOrganizationRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateOrganizationResponse
 */
export class AdminCreateOrganizationResponse extends Message<AdminCreateOrganizationResponse> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: libops.v1.admin.AdminFolderConfig folder = 2;
   */
  folder?: AdminFolderConfig;

  constructor(data?: PartialMessage<AdminCreateOrganizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateOrganizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "folder", kind: "message", T: AdminFolderConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateOrganizationResponse {
    return new AdminCreateOrganizationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateOrganizationResponse {
    return new AdminCreateOrganizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateOrganizationResponse {
    return new AdminCreateOrganizationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateOrganizationResponse | PlainMessage<AdminCreateOrganizationResponse> | undefined, b: AdminCreateOrganizationResponse | PlainMessage<AdminCreateOrganizationResponse> | undefined): boolean {
    return proto3.util.equals(AdminCreateOrganizationResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateOrganizationRequest
 */
export class AdminUpdateOrganizationRequest extends Message<AdminUpdateOrganizationRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: libops.v1.admin.AdminFolderConfig folder = 2;
   */
  folder?: AdminFolderConfig;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 3;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<AdminUpdateOrganizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateOrganizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "folder", kind: "message", T: AdminFolderConfig },
    { no: 3, name: "update_mask", kind: "message", T: FieldMask },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateOrganizationRequest {
    return new AdminUpdateOrganizationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateOrganizationRequest {
    return new AdminUpdateOrganizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateOrganizationRequest {
    return new AdminUpdateOrganizationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateOrganizationRequest | PlainMessage<AdminUpdateOrganizationRequest> | undefined, b: AdminUpdateOrganizationRequest | PlainMessage<AdminUpdateOrganizationRequest> | undefined): boolean {
    return proto3.util.equals(AdminUpdateOrganizationRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateOrganizationResponse
 */
export class AdminUpdateOrganizationResponse extends Message<AdminUpdateOrganizationResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminFolderConfig folder = 1;
   */
  folder?: AdminFolderConfig;

  constructor(data?: PartialMessage<AdminUpdateOrganizationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateOrganizationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "folder", kind: "message", T: AdminFolderConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateOrganizationResponse {
    return new AdminUpdateOrganizationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateOrganizationResponse {
    return new AdminUpdateOrganizationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateOrganizationResponse {
    return new AdminUpdateOrganizationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateOrganizationResponse | PlainMessage<AdminUpdateOrganizationResponse> | undefined, b: AdminUpdateOrganizationResponse | PlainMessage<AdminUpdateOrganizationResponse> | undefined): boolean {
    return proto3.util.equals(AdminUpdateOrganizationResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminDeleteOrganizationRequest
 */
export class AdminDeleteOrganizationRequest extends Message<AdminDeleteOrganizationRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  constructor(data?: PartialMessage<AdminDeleteOrganizationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminDeleteOrganizationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDeleteOrganizationRequest {
    return new AdminDeleteOrganizationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDeleteOrganizationRequest {
    return new AdminDeleteOrganizationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDeleteOrganizationRequest {
    return new AdminDeleteOrganizationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDeleteOrganizationRequest | PlainMessage<AdminDeleteOrganizationRequest> | undefined, b: AdminDeleteOrganizationRequest | PlainMessage<AdminDeleteOrganizationRequest> | undefined): boolean {
    return proto3.util.equals(AdminDeleteOrganizationRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListOrganizationsRequest
 */
export class AdminListOrganizationsRequest extends Message<AdminListOrganizationsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  /**
   * e.g., "gcp_parent=folders/123"
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string;

  constructor(data?: PartialMessage<AdminListOrganizationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListOrganizationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListOrganizationsRequest {
    return new AdminListOrganizationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListOrganizationsRequest {
    return new AdminListOrganizationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListOrganizationsRequest {
    return new AdminListOrganizationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListOrganizationsRequest | PlainMessage<AdminListOrganizationsRequest> | undefined, b: AdminListOrganizationsRequest | PlainMessage<AdminListOrganizationsRequest> | undefined): boolean {
    return proto3.util.equals(AdminListOrganizationsRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListOrganizationsResponse
 */
export class AdminListOrganizationsResponse extends Message<AdminListOrganizationsResponse> {
  /**
   * @generated from field: repeated libops.v1.admin.AdminFolderConfig organizations = 1;
   */
  organizations: AdminFolderConfig[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListOrganizationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListOrganizationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organizations", kind: "message", T: AdminFolderConfig, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListOrganizationsResponse {
    return new AdminListOrganizationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListOrganizationsResponse {
    return new AdminListOrganizationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListOrganizationsResponse {
    return new AdminListOrganizationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListOrganizationsResponse | PlainMessage<AdminListOrganizationsResponse> | undefined, b: AdminListOrganizationsResponse | PlainMessage<AdminListOrganizationsResponse> | undefined): boolean {
    return proto3.util.equals(AdminListOrganizationsResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListOrganizationProjectsRequest
 */
export class AdminListOrganizationProjectsRequest extends Message<AdminListOrganizationProjectsRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken = "";

  constructor(data?: PartialMessage<AdminListOrganizationProjectsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListOrganizationProjectsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListOrganizationProjectsRequest {
    return new AdminListOrganizationProjectsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListOrganizationProjectsRequest {
    return new AdminListOrganizationProjectsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListOrganizationProjectsRequest {
    return new AdminListOrganizationProjectsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListOrganizationProjectsRequest | PlainMessage<AdminListOrganizationProjectsRequest> | undefined, b: AdminListOrganizationProjectsRequest | PlainMessage<AdminListOrganizationProjectsRequest> | undefined): boolean {
    return proto3.util.equals(AdminListOrganizationProjectsRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListOrganizationProjectsResponse
 */
export class AdminListOrganizationProjectsResponse extends Message<AdminListOrganizationProjectsResponse> {
  /**
   * @generated from field: repeated string project_ids = 1;
   */
  projectIds: string[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListOrganizationProjectsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListOrganizationProjectsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "project_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListOrganizationProjectsResponse {
    return new AdminListOrganizationProjectsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListOrganizationProjectsResponse {
    return new AdminListOrganizationProjectsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListOrganizationProjectsResponse {
    return new AdminListOrganizationProjectsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListOrganizationProjectsResponse | PlainMessage<AdminListOrganizationProjectsResponse> | undefined, b: AdminListOrganizationProjectsResponse | PlainMessage<AdminListOrganizationProjectsResponse> | undefined): boolean {
    return proto3.util.equals(AdminListOrganizationProjectsResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminGetSiteRequest
 */
export class AdminGetSiteRequest extends Message<AdminGetSiteRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: string site_name = 3;
   */
  siteName = "";

  constructor(data?: PartialMessage<AdminGetSiteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetSiteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetSiteRequest {
    return new AdminGetSiteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetSiteRequest {
    return new AdminGetSiteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetSiteRequest {
    return new AdminGetSiteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetSiteRequest | PlainMessage<AdminGetSiteRequest> | undefined, b: AdminGetSiteRequest | PlainMessage<AdminGetSiteRequest> | undefined): boolean {
    return proto3.util.equals(AdminGetSiteRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminGetSiteResponse
 */
export class AdminGetSiteResponse extends Message<AdminGetSiteResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminSiteConfig site = 1;
   */
  site?: AdminSiteConfig;

  constructor(data?: PartialMessage<AdminGetSiteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminGetSiteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "site", kind: "message", T: AdminSiteConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminGetSiteResponse {
    return new AdminGetSiteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminGetSiteResponse {
    return new AdminGetSiteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminGetSiteResponse {
    return new AdminGetSiteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminGetSiteResponse | PlainMessage<AdminGetSiteResponse> | undefined, b: AdminGetSiteResponse | PlainMessage<AdminGetSiteResponse> | undefined): boolean {
    return proto3.util.equals(AdminGetSiteResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateSiteRequest
 */
export class AdminCreateSiteRequest extends Message<AdminCreateSiteRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: libops.v1.admin.AdminSiteConfig site = 3;
   */
  site?: AdminSiteConfig;

  constructor(data?: PartialMessage<AdminCreateSiteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateSiteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "site", kind: "message", T: AdminSiteConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateSiteRequest {
    return new AdminCreateSiteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateSiteRequest {
    return new AdminCreateSiteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateSiteRequest {
    return new AdminCreateSiteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateSiteRequest | PlainMessage<AdminCreateSiteRequest> | undefined, b: AdminCreateSiteRequest | PlainMessage<AdminCreateSiteRequest> | undefined): boolean {
    return proto3.util.equals(AdminCreateSiteRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminCreateSiteResponse
 */
export class AdminCreateSiteResponse extends Message<AdminCreateSiteResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminSiteConfig site = 1;
   */
  site?: AdminSiteConfig;

  constructor(data?: PartialMessage<AdminCreateSiteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminCreateSiteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "site", kind: "message", T: AdminSiteConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminCreateSiteResponse {
    return new AdminCreateSiteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminCreateSiteResponse {
    return new AdminCreateSiteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminCreateSiteResponse {
    return new AdminCreateSiteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminCreateSiteResponse | PlainMessage<AdminCreateSiteResponse> | undefined, b: AdminCreateSiteResponse | PlainMessage<AdminCreateSiteResponse> | undefined): boolean {
    return proto3.util.equals(AdminCreateSiteResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateSiteRequest
 */
export class AdminUpdateSiteRequest extends Message<AdminUpdateSiteRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: string site_name = 3;
   */
  siteName = "";

  /**
   * @generated from field: libops.v1.admin.AdminSiteConfig site = 4;
   */
  site?: AdminSiteConfig;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 5;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<AdminUpdateSiteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateSiteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "site", kind: "message", T: AdminSiteConfig },
    { no: 5, name: "update_mask", kind: "message", T: FieldMask },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateSiteRequest {
    return new AdminUpdateSiteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateSiteRequest {
    return new AdminUpdateSiteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateSiteRequest {
    return new AdminUpdateSiteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateSiteRequest | PlainMessage<AdminUpdateSiteRequest> | undefined, b: AdminUpdateSiteRequest | PlainMessage<AdminUpdateSiteRequest> | undefined): boolean {
    return proto3.util.equals(AdminUpdateSiteRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminUpdateSiteResponse
 */
export class AdminUpdateSiteResponse extends Message<AdminUpdateSiteResponse> {
  /**
   * @generated from field: libops.v1.admin.AdminSiteConfig site = 1;
   */
  site?: AdminSiteConfig;

  constructor(data?: PartialMessage<AdminUpdateSiteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminUpdateSiteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "site", kind: "message", T: AdminSiteConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUpdateSiteResponse {
    return new AdminUpdateSiteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUpdateSiteResponse {
    return new AdminUpdateSiteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUpdateSiteResponse {
    return new AdminUpdateSiteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUpdateSiteResponse | PlainMessage<AdminUpdateSiteResponse> | undefined, b: AdminUpdateSiteResponse | PlainMessage<AdminUpdateSiteResponse> | undefined): boolean {
    return proto3.util.equals(AdminUpdateSiteResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminDeleteSiteRequest
 */
export class AdminDeleteSiteRequest extends Message<AdminDeleteSiteRequest> {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId = "";

  /**
   * @generated from field: string project_id = 2;
   */
  projectId = "";

  /**
   * @generated from field: string site_name = 3;
   */
  siteName = "";

  constructor(data?: PartialMessage<AdminDeleteSiteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminDeleteSiteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "site_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDeleteSiteRequest {
    return new AdminDeleteSiteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDeleteSiteRequest {
    return new AdminDeleteSiteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDeleteSiteRequest {
    return new AdminDeleteSiteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDeleteSiteRequest | PlainMessage<AdminDeleteSiteRequest> | undefined, b: AdminDeleteSiteRequest | PlainMessage<AdminDeleteSiteRequest> | undefined): boolean {
    return proto3.util.equals(AdminDeleteSiteRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListSitesRequest
 */
export class AdminListSitesRequest extends Message<AdminListSitesRequest> {
  /**
   * @generated from field: optional string organization_id = 1;
   */
  organizationId?: string;

  /**
   * @generated from field: optional string project_id = 2;
   */
  projectId?: string;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 4;
   */
  pageToken = "";

  constructor(data?: PartialMessage<AdminListSitesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListSitesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "organization_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "project_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListSitesRequest {
    return new AdminListSitesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListSitesRequest {
    return new AdminListSitesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListSitesRequest {
    return new AdminListSitesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListSitesRequest | PlainMessage<AdminListSitesRequest> | undefined, b: AdminListSitesRequest | PlainMessage<AdminListSitesRequest> | undefined): boolean {
    return proto3.util.equals(AdminListSitesRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListSitesResponse
 */
export class AdminListSitesResponse extends Message<AdminListSitesResponse> {
  /**
   * @generated from field: repeated libops.v1.admin.AdminSiteConfig sites = 1;
   */
  sites: AdminSiteConfig[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListSitesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListSitesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sites", kind: "message", T: AdminSiteConfig, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListSitesResponse {
    return new AdminListSitesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListSitesResponse {
    return new AdminListSitesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListSitesResponse {
    return new AdminListSitesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListSitesResponse | PlainMessage<AdminListSitesResponse> | undefined, b: AdminListSitesResponse | PlainMessage<AdminListSitesResponse> | undefined): boolean {
    return proto3.util.equals(AdminListSitesResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListAllSitesRequest
 */
export class AdminListAllSitesRequest extends Message<AdminListAllSitesRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  /**
   * e.g., "organization_id=foo" or "status=active"
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string;

  constructor(data?: PartialMessage<AdminListAllSitesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListAllSitesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListAllSitesRequest {
    return new AdminListAllSitesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListAllSitesRequest {
    return new AdminListAllSitesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListAllSitesRequest {
    return new AdminListAllSitesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListAllSitesRequest | PlainMessage<AdminListAllSitesRequest> | undefined, b: AdminListAllSitesRequest | PlainMessage<AdminListAllSitesRequest> | undefined): boolean {
    return proto3.util.equals(AdminListAllSitesRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.AdminListAllSitesResponse
 */
export class AdminListAllSitesResponse extends Message<AdminListAllSitesResponse> {
  /**
   * @generated from field: repeated libops.v1.admin.AdminSiteConfig sites = 1;
   */
  sites: AdminSiteConfig[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<AdminListAllSitesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.AdminListAllSitesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sites", kind: "message", T: AdminSiteConfig, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminListAllSitesResponse {
    return new AdminListAllSitesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminListAllSitesResponse {
    return new AdminListAllSitesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminListAllSitesResponse {
    return new AdminListAllSitesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminListAllSitesResponse | PlainMessage<AdminListAllSitesResponse> | undefined, b: AdminListAllSitesResponse | PlainMessage<AdminListAllSitesResponse> | undefined): boolean {
    return proto3.util.equals(AdminListAllSitesResponse, a, b);
  }
}

