// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/organization_account_api.proto (package libops.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { AuthMethod } from "./common/types_pb.js";

/**
 * @generated from message libops.v1.OrganizationAccount
 */
export class OrganizationAccount extends Message<OrganizationAccount> {
  /**
   * Unique account identifier (UUID)
   *
   * @generated from field: string account_id = 1;
   */
  accountId = "";

  /**
   * User's email address
   *
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * Display name
   *
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * How the user authenticates
   *
   * @generated from field: libops.v1.common.AuthMethod auth_method = 4;
   */
  authMethod = AuthMethod.UNSPECIFIED;

  /**
   * Email verification status
   *
   * @generated from field: bool verified = 5;
   */
  verified = false;

  constructor(data?: PartialMessage<OrganizationAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.OrganizationAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "auth_method", kind: "enum", T: proto3.getEnumType(AuthMethod) },
    { no: 5, name: "verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OrganizationAccount {
    return new OrganizationAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OrganizationAccount {
    return new OrganizationAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OrganizationAccount {
    return new OrganizationAccount().fromJsonString(jsonString, options);
  }

  static equals(a: OrganizationAccount | PlainMessage<OrganizationAccount> | undefined, b: OrganizationAccount | PlainMessage<OrganizationAccount> | undefined): boolean {
    return proto3.util.equals(OrganizationAccount, a, b);
  }
}

/**
 * @generated from message libops.v1.GetAccountByEmailRequest
 */
export class GetAccountByEmailRequest extends Message<GetAccountByEmailRequest> {
  /**
   * @generated from field: string email = 1;
   */
  email = "";

  constructor(data?: PartialMessage<GetAccountByEmailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.GetAccountByEmailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByEmailRequest {
    return new GetAccountByEmailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByEmailRequest {
    return new GetAccountByEmailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByEmailRequest {
    return new GetAccountByEmailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAccountByEmailRequest | PlainMessage<GetAccountByEmailRequest> | undefined, b: GetAccountByEmailRequest | PlainMessage<GetAccountByEmailRequest> | undefined): boolean {
    return proto3.util.equals(GetAccountByEmailRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.GetAccountByEmailResponse
 */
export class GetAccountByEmailResponse extends Message<GetAccountByEmailResponse> {
  /**
   * @generated from field: libops.v1.OrganizationAccount account = 1;
   */
  account?: OrganizationAccount;

  constructor(data?: PartialMessage<GetAccountByEmailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.GetAccountByEmailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account", kind: "message", T: OrganizationAccount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByEmailResponse {
    return new GetAccountByEmailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByEmailResponse {
    return new GetAccountByEmailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByEmailResponse {
    return new GetAccountByEmailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAccountByEmailResponse | PlainMessage<GetAccountByEmailResponse> | undefined, b: GetAccountByEmailResponse | PlainMessage<GetAccountByEmailResponse> | undefined): boolean {
    return proto3.util.equals(GetAccountByEmailResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.ApiKeyMetadata
 */
export class ApiKeyMetadata extends Message<ApiKeyMetadata> {
  /**
   * UUID of the API key
   *
   * @generated from field: string api_key_id = 1;
   */
  apiKeyId = "";

  /**
   * User-friendly name
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Optional description
   *
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * Scope restrictions (empty = no restrictions)
   *
   * @generated from field: repeated string scopes = 4;
   */
  scopes: string[] = [];

  /**
   * Whether the key is active
   *
   * @generated from field: bool active = 5;
   */
  active = false;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 created_at = 6;
   */
  createdAt = protoInt64.zero;

  /**
   * Unix timestamp (0 if never used)
   *
   * @generated from field: int64 last_used_at = 7;
   */
  lastUsedAt = protoInt64.zero;

  constructor(data?: PartialMessage<ApiKeyMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.ApiKeyMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "last_used_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApiKeyMetadata {
    return new ApiKeyMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApiKeyMetadata {
    return new ApiKeyMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApiKeyMetadata {
    return new ApiKeyMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: ApiKeyMetadata | PlainMessage<ApiKeyMetadata> | undefined, b: ApiKeyMetadata | PlainMessage<ApiKeyMetadata> | undefined): boolean {
    return proto3.util.equals(ApiKeyMetadata, a, b);
  }
}

/**
 * @generated from message libops.v1.CreateApiKeyRequest
 */
export class CreateApiKeyRequest extends Message<CreateApiKeyRequest> {
  /**
   * User-friendly name for the key
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Optional description
   *
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * Optional scope restrictions (e.g., ["read:organization", "write:project"])
   *
   * @generated from field: repeated string scopes = 3;
   */
  scopes: string[] = [];

  constructor(data?: PartialMessage<CreateApiKeyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.CreateApiKeyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateApiKeyRequest {
    return new CreateApiKeyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateApiKeyRequest {
    return new CreateApiKeyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateApiKeyRequest {
    return new CreateApiKeyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateApiKeyRequest | PlainMessage<CreateApiKeyRequest> | undefined, b: CreateApiKeyRequest | PlainMessage<CreateApiKeyRequest> | undefined): boolean {
    return proto3.util.equals(CreateApiKeyRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.CreateApiKeyResponse
 */
export class CreateApiKeyResponse extends Message<CreateApiKeyResponse> {
  /**
   * UUID of the created key
   *
   * @generated from field: string api_key_id = 1;
   */
  apiKeyId = "";

  /**
   * The actual key value (only returned once!)
   *
   * @generated from field: string api_key = 2;
   */
  apiKey = "";

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * @generated from field: repeated string scopes = 5;
   */
  scopes: string[] = [];

  /**
   * @generated from field: int64 created_at = 6;
   */
  createdAt = protoInt64.zero;

  constructor(data?: PartialMessage<CreateApiKeyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.CreateApiKeyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "api_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateApiKeyResponse {
    return new CreateApiKeyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateApiKeyResponse {
    return new CreateApiKeyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateApiKeyResponse {
    return new CreateApiKeyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateApiKeyResponse | PlainMessage<CreateApiKeyResponse> | undefined, b: CreateApiKeyResponse | PlainMessage<CreateApiKeyResponse> | undefined): boolean {
    return proto3.util.equals(CreateApiKeyResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.ListApiKeysRequest
 */
export class ListApiKeysRequest extends Message<ListApiKeysRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * NO account_id filter - always lists the authenticated user's keys
   *
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListApiKeysRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.ListApiKeysRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListApiKeysRequest {
    return new ListApiKeysRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListApiKeysRequest {
    return new ListApiKeysRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListApiKeysRequest {
    return new ListApiKeysRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListApiKeysRequest | PlainMessage<ListApiKeysRequest> | undefined, b: ListApiKeysRequest | PlainMessage<ListApiKeysRequest> | undefined): boolean {
    return proto3.util.equals(ListApiKeysRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.ListApiKeysResponse
 */
export class ListApiKeysResponse extends Message<ListApiKeysResponse> {
  /**
   * @generated from field: repeated libops.v1.ApiKeyMetadata api_keys = 1;
   */
  apiKeys: ApiKeyMetadata[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListApiKeysResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.ListApiKeysResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_keys", kind: "message", T: ApiKeyMetadata, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListApiKeysResponse {
    return new ListApiKeysResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListApiKeysResponse {
    return new ListApiKeysResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListApiKeysResponse {
    return new ListApiKeysResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListApiKeysResponse | PlainMessage<ListApiKeysResponse> | undefined, b: ListApiKeysResponse | PlainMessage<ListApiKeysResponse> | undefined): boolean {
    return proto3.util.equals(ListApiKeysResponse, a, b);
  }
}

/**
 * @generated from message libops.v1.RevokeApiKeyRequest
 */
export class RevokeApiKeyRequest extends Message<RevokeApiKeyRequest> {
  /**
   * UUID of the key to revoke
   *
   * @generated from field: string api_key_id = 1;
   */
  apiKeyId = "";

  constructor(data?: PartialMessage<RevokeApiKeyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.RevokeApiKeyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "api_key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeApiKeyRequest {
    return new RevokeApiKeyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeApiKeyRequest {
    return new RevokeApiKeyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeApiKeyRequest {
    return new RevokeApiKeyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeApiKeyRequest | PlainMessage<RevokeApiKeyRequest> | undefined, b: RevokeApiKeyRequest | PlainMessage<RevokeApiKeyRequest> | undefined): boolean {
    return proto3.util.equals(RevokeApiKeyRequest, a, b);
  }
}

/**
 * @generated from message libops.v1.RevokeApiKeyResponse
 */
export class RevokeApiKeyResponse extends Message<RevokeApiKeyResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<RevokeApiKeyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.RevokeApiKeyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeApiKeyResponse {
    return new RevokeApiKeyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeApiKeyResponse {
    return new RevokeApiKeyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeApiKeyResponse {
    return new RevokeApiKeyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeApiKeyResponse | PlainMessage<RevokeApiKeyResponse> | undefined, b: RevokeApiKeyResponse | PlainMessage<RevokeApiKeyResponse> | undefined): boolean {
    return proto3.util.equals(RevokeApiKeyResponse, a, b);
  }
}

