// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file libops/v1/settings.proto (package libops.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateOrganizationSettingRequest, CreateOrganizationSettingResponse, CreateProjectSettingRequest, CreateProjectSettingResponse, CreateSiteSettingRequest, CreateSiteSettingResponse, DeleteOrganizationSettingRequest, DeleteProjectSettingRequest, DeleteSiteSettingRequest, GetOrganizationSettingRequest, GetOrganizationSettingResponse, GetProjectSettingRequest, GetProjectSettingResponse, GetSiteSettingRequest, GetSiteSettingResponse, ListOrganizationSettingsRequest, ListOrganizationSettingsResponse, ListProjectSettingsRequest, ListProjectSettingsResponse, ListSiteSettingsRequest, ListSiteSettingsResponse, UpdateOrganizationSettingRequest, UpdateOrganizationSettingResponse, UpdateProjectSettingRequest, UpdateProjectSettingResponse, UpdateSiteSettingRequest, UpdateSiteSettingResponse } from "./settings_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { Empty } from "../../google/protobuf/empty_pb.js";

/**
 * OrganizationSettingService manages organization-level settings
 *
 * @generated from service libops.v1.OrganizationSettingService
 */
export const OrganizationSettingService = {
  typeName: "libops.v1.OrganizationSettingService",
  methods: {
    /**
     * Create an organization setting
     *
     * @generated from rpc libops.v1.OrganizationSettingService.CreateOrganizationSetting
     */
    createOrganizationSetting: {
      name: "CreateOrganizationSetting",
      I: CreateOrganizationSettingRequest,
      O: CreateOrganizationSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get an organization setting
     *
     * @generated from rpc libops.v1.OrganizationSettingService.GetOrganizationSetting
     */
    getOrganizationSetting: {
      name: "GetOrganizationSetting",
      I: GetOrganizationSettingRequest,
      O: GetOrganizationSettingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List organization settings
     *
     * @generated from rpc libops.v1.OrganizationSettingService.ListOrganizationSettings
     */
    listOrganizationSettings: {
      name: "ListOrganizationSettings",
      I: ListOrganizationSettingsRequest,
      O: ListOrganizationSettingsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Update an organization setting
     *
     * @generated from rpc libops.v1.OrganizationSettingService.UpdateOrganizationSetting
     */
    updateOrganizationSetting: {
      name: "UpdateOrganizationSetting",
      I: UpdateOrganizationSettingRequest,
      O: UpdateOrganizationSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an organization setting
     *
     * @generated from rpc libops.v1.OrganizationSettingService.DeleteOrganizationSetting
     */
    deleteOrganizationSetting: {
      name: "DeleteOrganizationSetting",
      I: DeleteOrganizationSettingRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * ProjectSettingService manages project-level settings
 *
 * @generated from service libops.v1.ProjectSettingService
 */
export const ProjectSettingService = {
  typeName: "libops.v1.ProjectSettingService",
  methods: {
    /**
     * Create a project setting
     *
     * @generated from rpc libops.v1.ProjectSettingService.CreateProjectSetting
     */
    createProjectSetting: {
      name: "CreateProjectSetting",
      I: CreateProjectSettingRequest,
      O: CreateProjectSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get a project setting
     *
     * @generated from rpc libops.v1.ProjectSettingService.GetProjectSetting
     */
    getProjectSetting: {
      name: "GetProjectSetting",
      I: GetProjectSettingRequest,
      O: GetProjectSettingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List project settings
     *
     * @generated from rpc libops.v1.ProjectSettingService.ListProjectSettings
     */
    listProjectSettings: {
      name: "ListProjectSettings",
      I: ListProjectSettingsRequest,
      O: ListProjectSettingsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Update a project setting
     *
     * @generated from rpc libops.v1.ProjectSettingService.UpdateProjectSetting
     */
    updateProjectSetting: {
      name: "UpdateProjectSetting",
      I: UpdateProjectSettingRequest,
      O: UpdateProjectSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a project setting
     *
     * @generated from rpc libops.v1.ProjectSettingService.DeleteProjectSetting
     */
    deleteProjectSetting: {
      name: "DeleteProjectSetting",
      I: DeleteProjectSettingRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * SiteSettingService manages site-level settings
 *
 * @generated from service libops.v1.SiteSettingService
 */
export const SiteSettingService = {
  typeName: "libops.v1.SiteSettingService",
  methods: {
    /**
     * Create a site setting
     *
     * @generated from rpc libops.v1.SiteSettingService.CreateSiteSetting
     */
    createSiteSetting: {
      name: "CreateSiteSetting",
      I: CreateSiteSettingRequest,
      O: CreateSiteSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get a site setting
     *
     * @generated from rpc libops.v1.SiteSettingService.GetSiteSetting
     */
    getSiteSetting: {
      name: "GetSiteSetting",
      I: GetSiteSettingRequest,
      O: GetSiteSettingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * List site settings
     *
     * @generated from rpc libops.v1.SiteSettingService.ListSiteSettings
     */
    listSiteSettings: {
      name: "ListSiteSettings",
      I: ListSiteSettingsRequest,
      O: ListSiteSettingsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Update a site setting
     *
     * @generated from rpc libops.v1.SiteSettingService.UpdateSiteSetting
     */
    updateSiteSetting: {
      name: "UpdateSiteSetting",
      I: UpdateSiteSettingRequest,
      O: UpdateSiteSettingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a site setting
     *
     * @generated from rpc libops.v1.SiteSettingService.DeleteSiteSetting
     */
    deleteSiteSetting: {
      name: "DeleteSiteSetting",
      I: DeleteSiteSettingRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

