// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/admin/project.proto (package libops.v1.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ProjectConfig } from "../common/project_pb.js";

/**
 * AdminProjectConfig extends the organization-facing config with sensitive fields
 *
 * @generated from message libops.v1.admin.AdminProjectConfig
 */
export class AdminProjectConfig extends Message<AdminProjectConfig> {
  /**
   * Organization-safe fields (embedded)
   *
   * @generated from field: libops.v1.common.ProjectConfig config = 1;
   */
  config?: ProjectConfig;

  /**
   * @generated from field: string billing_account = 2;
   */
  billingAccount = "";

  /**
   * GitHub integration
   *
   * @generated from field: optional string github_webhook_url = 3;
   */
  githubWebhookUrl?: string;

  /**
   * Sensitive
   *
   * @generated from field: optional string github_webhook_secret = 4;
   */
  githubWebhookSecret?: string;

  /**
   * Sensitive
   *
   * @generated from field: optional string host_docker_config = 5;
   */
  hostDockerConfig?: string;

  /**
   * GCP-managed resources (output from orchestration)
   *
   * Set after project creation
   *
   * @generated from field: optional string gcp_project_id = 6;
   */
  gcpProjectId?: string;

  /**
   * Set after project creation
   *
   * @generated from field: optional string gcp_project_number = 7;
   */
  gcpProjectNumber?: string;

  /**
   * Set after GitHub team creation
   *
   * @generated from field: optional string github_team_id = 8;
   */
  githubTeamId?: string;

  /**
   * Flag to identify if this is the organization's libops project (for vault, etc.)
   *
   * @generated from field: bool organization_project = 9;
   */
  organizationProject = false;

  constructor(data?: PartialMessage<AdminProjectConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.admin.AdminProjectConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config", kind: "message", T: ProjectConfig },
    { no: 2, name: "billing_account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "github_webhook_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "github_webhook_secret", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "host_docker_config", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "gcp_project_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "gcp_project_number", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "github_team_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "organization_project", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminProjectConfig {
    return new AdminProjectConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminProjectConfig {
    return new AdminProjectConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminProjectConfig {
    return new AdminProjectConfig().fromJsonString(jsonString, options);
  }

  static equals(a: AdminProjectConfig | PlainMessage<AdminProjectConfig> | undefined, b: AdminProjectConfig | PlainMessage<AdminProjectConfig> | undefined): boolean {
    return proto3.util.equals(AdminProjectConfig, a, b);
  }
}

