// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file libops/v1/options/scope.proto (package libops.v1.options, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { MethodOptions } from "../../../google/protobuf/descriptor_pb.js";

/**
 * ResourceType represents the hierarchical level of a resource
 * The hierarchy is: SYSTEM > ORGANIZATION > PROJECT > SITE
 *
 * @generated from enum libops.v1.options.ResourceType
 */
export enum ResourceType {
  /**
   * @generated from enum value: RESOURCE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * System-wide operations (admin only)
   *
   * @generated from enum value: RESOURCE_TYPE_SYSTEM = 1;
   */
  SYSTEM = 1,

  /**
   * Account/user level
   *
   * @generated from enum value: RESOURCE_TYPE_ACCOUNT = 2;
   */
  ACCOUNT = 2,

  /**
   * Organization level
   *
   * @generated from enum value: RESOURCE_TYPE_ORGANIZATION = 3;
   */
  ORGANIZATION = 3,

  /**
   * Project level
   *
   * @generated from enum value: RESOURCE_TYPE_PROJECT = 4;
   */
  PROJECT = 4,

  /**
   * Site level
   *
   * @generated from enum value: RESOURCE_TYPE_SITE = 5;
   */
  SITE = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(ResourceType)
proto3.util.setEnumType(ResourceType, "libops.v1.options.ResourceType", [
  { no: 0, name: "RESOURCE_TYPE_UNSPECIFIED" },
  { no: 1, name: "RESOURCE_TYPE_SYSTEM" },
  { no: 2, name: "RESOURCE_TYPE_ACCOUNT" },
  { no: 3, name: "RESOURCE_TYPE_ORGANIZATION" },
  { no: 4, name: "RESOURCE_TYPE_PROJECT" },
  { no: 5, name: "RESOURCE_TYPE_SITE" },
]);

/**
 * AccessLevel represents the type of access required
 * Higher levels include permissions of lower levels
 * ADMIN > WRITE > READ
 *
 * @generated from enum libops.v1.options.AccessLevel
 */
export enum AccessLevel {
  /**
   * @generated from enum value: ACCESS_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Read-only access
   *
   * @generated from enum value: ACCESS_LEVEL_READ = 1;
   */
  READ = 1,

  /**
   * Read and write access
   *
   * @generated from enum value: ACCESS_LEVEL_WRITE = 2;
   */
  WRITE = 2,

  /**
   * Full administrative access
   *
   * @generated from enum value: ACCESS_LEVEL_ADMIN = 3;
   */
  ADMIN = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AccessLevel)
proto3.util.setEnumType(AccessLevel, "libops.v1.options.AccessLevel", [
  { no: 0, name: "ACCESS_LEVEL_UNSPECIFIED" },
  { no: 1, name: "ACCESS_LEVEL_READ" },
  { no: 2, name: "ACCESS_LEVEL_WRITE" },
  { no: 3, name: "ACCESS_LEVEL_ADMIN" },
]);

/**
 * ScopeRule defines the authorization requirements for an RPC method
 * This annotation tells the authorization middleware what level of access is required
 *
 * @generated from message libops.v1.options.ScopeRule
 */
export class ScopeRule extends Message<ScopeRule> {
  /**
   * The resource type this method operates on
   *
   * @generated from field: libops.v1.options.ResourceType resource = 1;
   */
  resource = ResourceType.UNSPECIFIED;

  /**
   * The minimum access level required
   *
   * @generated from field: libops.v1.options.AccessLevel level = 2;
   */
  level = AccessLevel.UNSPECIFIED;

  /**
   * Optional: if true, allows parent resource access to satisfy this requirement
   * For example, ORGANIZATION_ADMIN can access PROJECT_READ if allow_parent_access=true
   * Default is true to maintain hierarchical access model
   *
   * @generated from field: bool allow_parent_access = 3;
   */
  allowParentAccess = false;

  /**
   * OAuth scope strings required for this endpoint
   * These are the actual OAuth 2.0 scope values that will appear in documentation
   * Example: ["read:organization", "read:members"]
   *
   * @generated from field: repeated string oauth_scopes = 4;
   */
  oauthScopes: string[] = [];

  /**
   * Optional: field name in the request message containing the resource ID to check membership
   * If specified, the interceptor will automatically check membership for this resource
   * Examples: "organization_id", "project_id", "site_id"
   * The interceptor will extract this field from the request and verify the user is a member
   *
   * @generated from field: string resource_id_field = 5;
   */
  resourceIdField = "";

  /**
   * Optional: for create operations, this specifies the parent resource field to check
   * Example: for CreateProject, parent_resource_id_field = "organization_id"
   * This ensures user is a member of the parent before allowing creation
   *
   * @generated from field: string parent_resource_id_field = 6;
   */
  parentResourceIdField = "";

  /**
   * Optional: the parent resource type (only needed if parent_resource_id_field is set)
   *
   * @generated from field: libops.v1.options.ResourceType parent_resource = 7;
   */
  parentResource = ResourceType.UNSPECIFIED;

  constructor(data?: PartialMessage<ScopeRule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "libops.v1.options.ScopeRule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource", kind: "enum", T: proto3.getEnumType(ResourceType) },
    { no: 2, name: "level", kind: "enum", T: proto3.getEnumType(AccessLevel) },
    { no: 3, name: "allow_parent_access", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "oauth_scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "resource_id_field", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "parent_resource_id_field", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "parent_resource", kind: "enum", T: proto3.getEnumType(ResourceType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ScopeRule {
    return new ScopeRule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ScopeRule {
    return new ScopeRule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ScopeRule {
    return new ScopeRule().fromJsonString(jsonString, options);
  }

  static equals(a: ScopeRule | PlainMessage<ScopeRule> | undefined, b: ScopeRule | PlainMessage<ScopeRule> | undefined): boolean {
    return proto3.util.equals(ScopeRule, a, b);
  }
}

/**
 * The scope rule that applies to this RPC method
 *
 * Pick a unique field number (50001 is used by audit)
 *
 * @generated from extension: libops.v1.options.ScopeRule required_scope = 50002;
 */
export const required_scope = proto3.makeExtension<MethodOptions, ScopeRule>(
  "libops.v1.options.required_scope", 
  MethodOptions, 
  () => ({ no: 50002, kind: "message", T: ScopeRule }),
);

