// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/libops/api/db/types"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (
  public_id, account_id, ` + "`" + `name` + "`" + `, description, scopes, created_at, expires_at, active, created_by
) VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, NOW(), ?, ?, ?)
`

type CreateAPIKeyParams struct {
	PublicID    string         `json:"public_id"`
	AccountID   int64          `json:"account_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Scopes      types.RawJSON  `json:"scopes"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	Active      bool           `json:"active"`
	CreatedBy   sql.NullInt64  `json:"created_by"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.PublicID,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.Scopes,
		arg.ExpiresAt,
		arg.Active,
		arg.CreatedBy,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE public_id = UUID_TO_BIN(?)
`

func (q *Queries) DeleteAPIKey(ctx context.Context, publicID string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, publicID)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, account_id, ` + "`" + `name` + "`" + `, description,
       COALESCE(scopes, '[]') as scopes,
       created_at, last_used_at, expires_at, active, created_by
FROM api_keys WHERE id = ?
`

type GetAPIKeyByIDRow struct {
	ID          int64           `json:"id"`
	PublicID    string          `json:"public_id"`
	AccountID   int64           `json:"account_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Scopes      json.RawMessage `json:"scopes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	LastUsedAt  sql.NullTime    `json:"last_used_at"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Active      bool            `json:"active"`
	CreatedBy   sql.NullInt64   `json:"created_by"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedBy,
	)
	return i, err
}

const getAPIKeyByUUID = `-- name: GetAPIKeyByUUID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, account_id, ` + "`" + `name` + "`" + `, description,
       COALESCE(scopes, '[]') as scopes,
       created_at, last_used_at, expires_at, active, created_by
FROM api_keys WHERE public_id = UUID_TO_BIN(?)
`

type GetAPIKeyByUUIDRow struct {
	ID          int64           `json:"id"`
	PublicID    string          `json:"public_id"`
	AccountID   int64           `json:"account_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Scopes      json.RawMessage `json:"scopes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	LastUsedAt  sql.NullTime    `json:"last_used_at"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Active      bool            `json:"active"`
	CreatedBy   sql.NullInt64   `json:"created_by"`
}

func (q *Queries) GetAPIKeyByUUID(ctx context.Context, publicID string) (GetAPIKeyByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByUUID, publicID)
	var i GetAPIKeyByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedBy,
	)
	return i, err
}

const getActiveAPIKeyByUUID = `-- name: GetActiveAPIKeyByUUID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, account_id, ` + "`" + `name` + "`" + `, description,
       COALESCE(scopes, '[]') as scopes,
       created_at, last_used_at, expires_at, active, created_by
FROM api_keys
WHERE public_id = UUID_TO_BIN(?)
  AND active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

type GetActiveAPIKeyByUUIDRow struct {
	ID          int64           `json:"id"`
	PublicID    string          `json:"public_id"`
	AccountID   int64           `json:"account_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Scopes      json.RawMessage `json:"scopes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	LastUsedAt  sql.NullTime    `json:"last_used_at"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Active      bool            `json:"active"`
	CreatedBy   sql.NullInt64   `json:"created_by"`
}

func (q *Queries) GetActiveAPIKeyByUUID(ctx context.Context, publicID string) (GetActiveAPIKeyByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPIKeyByUUID, publicID)
	var i GetActiveAPIKeyByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedBy,
	)
	return i, err
}

const updateAPIKeyActive = `-- name: UpdateAPIKeyActive :exec
UPDATE api_keys SET
  active = ?
WHERE public_id = UUID_TO_BIN(?)
`

type UpdateAPIKeyActiveParams struct {
	Active   bool   `json:"active"`
	PublicID string `json:"public_id"`
}

func (q *Queries) UpdateAPIKeyActive(ctx context.Context, arg UpdateAPIKeyActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyActive, arg.Active, arg.PublicID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET
  last_used_at = NOW()
WHERE public_id = UUID_TO_BIN(?)
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, publicID string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, publicID)
	return err
}
