// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit (
  account_id, entity_id, entity_type, event_name, event_data
) VALUES (?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	AccountID  int64           `json:"account_id"`
	EntityID   int64           `json:"entity_id"`
	EntityType AuditEntityType `json:"entity_type"`
	EventName  string          `json:"event_name"`
	EventData  []byte          `json:"event_data"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.AccountID,
		arg.EntityID,
		arg.EntityType,
		arg.EventName,
		arg.EventData,
	)
	return err
}
