// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package db

import (
	"context"
	"database/sql"
)

const createOnboardingSession = `-- name: CreateOnboardingSession :execresult
INSERT INTO onboarding_sessions (
  public_id, account_id, org_name, machine_type, machine_price_id, disk_size_gb,
  stripe_checkout_session_id, stripe_subscription_id, organization_id,
  project_name, gcp_country, gcp_region, site_name, github_repo_url, port, firewall_ip,
  current_step, completed, expires_at, created_at, updated_at
) VALUES (UUID_TO_BIN(UUID_V7()), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateOnboardingSessionParams struct {
	AccountID               int64          `json:"account_id"`
	OrgName                 sql.NullString `json:"org_name"`
	MachineType             sql.NullString `json:"machine_type"`
	MachinePriceID          sql.NullString `json:"machine_price_id"`
	DiskSizeGb              sql.NullInt32  `json:"disk_size_gb"`
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
	StripeSubscriptionID    sql.NullString `json:"stripe_subscription_id"`
	OrganizationID          sql.NullInt64  `json:"organization_id"`
	ProjectName             sql.NullString `json:"project_name"`
	GcpCountry              sql.NullString `json:"gcp_country"`
	GcpRegion               sql.NullString `json:"gcp_region"`
	SiteName                sql.NullString `json:"site_name"`
	GithubRepoUrl           sql.NullString `json:"github_repo_url"`
	Port                    sql.NullInt32  `json:"port"`
	FirewallIp              sql.NullString `json:"firewall_ip"`
	CurrentStep             sql.NullInt32  `json:"current_step"`
	Completed               sql.NullBool   `json:"completed"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateOnboardingSession(ctx context.Context, arg CreateOnboardingSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOnboardingSession,
		arg.AccountID,
		arg.OrgName,
		arg.MachineType,
		arg.MachinePriceID,
		arg.DiskSizeGb,
		arg.StripeCheckoutSessionID,
		arg.StripeSubscriptionID,
		arg.OrganizationID,
		arg.ProjectName,
		arg.GcpCountry,
		arg.GcpRegion,
		arg.SiteName,
		arg.GithubRepoUrl,
		arg.Port,
		arg.FirewallIp,
		arg.CurrentStep,
		arg.Completed,
		arg.ExpiresAt,
	)
}

const deleteExpiredOnboardingSessions = `-- name: DeleteExpiredOnboardingSessions :exec
DELETE FROM onboarding_sessions WHERE expires_at < NOW() AND completed = FALSE
`

func (q *Queries) DeleteExpiredOnboardingSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOnboardingSessions)
	return err
}

const getOnboardingSession = `-- name: GetOnboardingSession :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, account_id, org_name,
       CASE WHEN organization_public_id IS NULL THEN NULL ELSE BIN_TO_UUID(organization_public_id) END AS organization_public_id,
       machine_type, machine_price_id, disk_size_gb,
       stripe_checkout_session_id, stripe_checkout_url, stripe_subscription_id, organization_id,
       project_name, gcp_country, gcp_region, site_name, github_repo_url, port, firewall_ip,
       current_step, completed, expires_at, created_at, updated_at
FROM onboarding_sessions WHERE public_id = UUID_TO_BIN(?)
`

type GetOnboardingSessionRow struct {
	ID                      int64          `json:"id"`
	PublicID                string         `json:"public_id"`
	AccountID               int64          `json:"account_id"`
	OrgName                 sql.NullString `json:"org_name"`
	OrganizationPublicID    interface{}    `json:"organization_public_id"`
	MachineType             sql.NullString `json:"machine_type"`
	MachinePriceID          sql.NullString `json:"machine_price_id"`
	DiskSizeGb              sql.NullInt32  `json:"disk_size_gb"`
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
	StripeCheckoutUrl       sql.NullString `json:"stripe_checkout_url"`
	StripeSubscriptionID    sql.NullString `json:"stripe_subscription_id"`
	OrganizationID          sql.NullInt64  `json:"organization_id"`
	ProjectName             sql.NullString `json:"project_name"`
	GcpCountry              sql.NullString `json:"gcp_country"`
	GcpRegion               sql.NullString `json:"gcp_region"`
	SiteName                sql.NullString `json:"site_name"`
	GithubRepoUrl           sql.NullString `json:"github_repo_url"`
	Port                    sql.NullInt32  `json:"port"`
	FirewallIp              sql.NullString `json:"firewall_ip"`
	CurrentStep             sql.NullInt32  `json:"current_step"`
	Completed               sql.NullBool   `json:"completed"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetOnboardingSession(ctx context.Context, publicID string) (GetOnboardingSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getOnboardingSession, publicID)
	var i GetOnboardingSessionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AccountID,
		&i.OrgName,
		&i.OrganizationPublicID,
		&i.MachineType,
		&i.MachinePriceID,
		&i.DiskSizeGb,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutUrl,
		&i.StripeSubscriptionID,
		&i.OrganizationID,
		&i.ProjectName,
		&i.GcpCountry,
		&i.GcpRegion,
		&i.SiteName,
		&i.GithubRepoUrl,
		&i.Port,
		&i.FirewallIp,
		&i.CurrentStep,
		&i.Completed,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOnboardingSession = `-- name: UpdateOnboardingSession :exec
UPDATE onboarding_sessions SET
  org_name = ?,
  organization_public_id = IF(? = '', NULL, UUID_TO_BIN(?)),
  machine_type = ?,
  machine_price_id = ?,
  disk_size_gb = ?,
  stripe_checkout_session_id = ?,
  stripe_checkout_url = ?,
  stripe_subscription_id = ?,
  organization_id = ?,
  project_name = ?,
  gcp_country = ?,
  gcp_region = ?,
  site_name = ?,
  github_repo_url = ?,
  port = ?,
  firewall_ip = ?,
  current_step = ?,
  completed = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateOnboardingSessionParams struct {
	OrgName                 sql.NullString `json:"org_name"`
	OrgUuid                 string         `json:"org_uuid"`
	MachineType             sql.NullString `json:"machine_type"`
	MachinePriceID          sql.NullString `json:"machine_price_id"`
	DiskSizeGb              sql.NullInt32  `json:"disk_size_gb"`
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
	StripeCheckoutUrl       sql.NullString `json:"stripe_checkout_url"`
	StripeSubscriptionID    sql.NullString `json:"stripe_subscription_id"`
	OrganizationID          sql.NullInt64  `json:"organization_id"`
	ProjectName             sql.NullString `json:"project_name"`
	GcpCountry              sql.NullString `json:"gcp_country"`
	GcpRegion               sql.NullString `json:"gcp_region"`
	SiteName                sql.NullString `json:"site_name"`
	GithubRepoUrl           sql.NullString `json:"github_repo_url"`
	Port                    sql.NullInt32  `json:"port"`
	FirewallIp              sql.NullString `json:"firewall_ip"`
	CurrentStep             sql.NullInt32  `json:"current_step"`
	Completed               sql.NullBool   `json:"completed"`
	ID                      int64          `json:"id"`
}

func (q *Queries) UpdateOnboardingSession(ctx context.Context, arg UpdateOnboardingSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateOnboardingSession,
		arg.OrgName,
		arg.OrgUuid,
		arg.OrgUuid,
		arg.MachineType,
		arg.MachinePriceID,
		arg.DiskSizeGb,
		arg.StripeCheckoutSessionID,
		arg.StripeCheckoutUrl,
		arg.StripeSubscriptionID,
		arg.OrganizationID,
		arg.ProjectName,
		arg.GcpCountry,
		arg.GcpRegion,
		arg.SiteName,
		arg.GithubRepoUrl,
		arg.Port,
		arg.FirewallIp,
		arg.CurrentStep,
		arg.Completed,
		arg.ID,
	)
	return err
}
