// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const createOrganizationSetting = `-- name: CreateOrganizationSetting :exec

INSERT INTO organization_settings (
    public_id, organization_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
) VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, ?, ?, NOW(), NOW(), ?, ?)
`

type CreateOrganizationSettingParams struct {
	PublicID       string                         `json:"public_id"`
	OrganizationID int64                          `json:"organization_id"`
	SettingKey     string                         `json:"setting_key"`
	SettingValue   string                         `json:"setting_value"`
	Editable       sql.NullBool                   `json:"editable"`
	Description    sql.NullString                 `json:"description"`
	Status         NullOrganizationSettingsStatus `json:"status"`
	CreatedBy      sql.NullInt64                  `json:"created_by"`
	UpdatedBy      sql.NullInt64                  `json:"updated_by"`
}

// ============================================================================
// ORGANIZATION SETTINGS
// ============================================================================
func (q *Queries) CreateOrganizationSetting(ctx context.Context, arg CreateOrganizationSettingParams) error {
	_, err := q.db.ExecContext(ctx, createOrganizationSetting,
		arg.PublicID,
		arg.OrganizationID,
		arg.SettingKey,
		arg.SettingValue,
		arg.Editable,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const createProjectSetting = `-- name: CreateProjectSetting :exec

INSERT INTO project_settings (
    public_id, project_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
) VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, ?, ?, NOW(), NOW(), ?, ?)
`

type CreateProjectSettingParams struct {
	PublicID     string                    `json:"public_id"`
	ProjectID    int64                     `json:"project_id"`
	SettingKey   string                    `json:"setting_key"`
	SettingValue string                    `json:"setting_value"`
	Editable     sql.NullBool              `json:"editable"`
	Description  sql.NullString            `json:"description"`
	Status       NullProjectSettingsStatus `json:"status"`
	CreatedBy    sql.NullInt64             `json:"created_by"`
	UpdatedBy    sql.NullInt64             `json:"updated_by"`
}

// ============================================================================
// PROJECT SETTINGS
// ============================================================================
func (q *Queries) CreateProjectSetting(ctx context.Context, arg CreateProjectSettingParams) error {
	_, err := q.db.ExecContext(ctx, createProjectSetting,
		arg.PublicID,
		arg.ProjectID,
		arg.SettingKey,
		arg.SettingValue,
		arg.Editable,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const createSiteSetting = `-- name: CreateSiteSetting :exec

INSERT INTO site_settings (
    public_id, site_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
) VALUES (UUID_TO_BIN(?), ?, ?, ?, ?, ?, ?, NOW(), NOW(), ?, ?)
`

type CreateSiteSettingParams struct {
	PublicID     string                 `json:"public_id"`
	SiteID       int64                  `json:"site_id"`
	SettingKey   string                 `json:"setting_key"`
	SettingValue string                 `json:"setting_value"`
	Editable     sql.NullBool           `json:"editable"`
	Description  sql.NullString         `json:"description"`
	Status       NullSiteSettingsStatus `json:"status"`
	CreatedBy    sql.NullInt64          `json:"created_by"`
	UpdatedBy    sql.NullInt64          `json:"updated_by"`
}

// ============================================================================
// SITE SETTINGS
// ============================================================================
func (q *Queries) CreateSiteSetting(ctx context.Context, arg CreateSiteSettingParams) error {
	_, err := q.db.ExecContext(ctx, createSiteSetting,
		arg.PublicID,
		arg.SiteID,
		arg.SettingKey,
		arg.SettingValue,
		arg.Editable,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const deleteOrganizationSetting = `-- name: DeleteOrganizationSetting :exec
UPDATE organization_settings
SET status = 'deleted', updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type DeleteOrganizationSettingParams struct {
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	PublicID  string        `json:"public_id"`
}

func (q *Queries) DeleteOrganizationSetting(ctx context.Context, arg DeleteOrganizationSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrganizationSetting, arg.UpdatedBy, arg.PublicID)
	return err
}

const deleteProjectSetting = `-- name: DeleteProjectSetting :exec
UPDATE project_settings
SET status = 'deleted', updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type DeleteProjectSettingParams struct {
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	PublicID  string        `json:"public_id"`
}

func (q *Queries) DeleteProjectSetting(ctx context.Context, arg DeleteProjectSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectSetting, arg.UpdatedBy, arg.PublicID)
	return err
}

const deleteSiteSetting = `-- name: DeleteSiteSetting :exec
UPDATE site_settings
SET status = 'deleted', updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type DeleteSiteSettingParams struct {
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	PublicID  string        `json:"public_id"`
}

func (q *Queries) DeleteSiteSetting(ctx context.Context, arg DeleteSiteSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSiteSetting, arg.UpdatedBy, arg.PublicID)
	return err
}

const getOrganizationSetting = `-- name: GetOrganizationSetting :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, organization_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM organization_settings
WHERE organization_id = ? AND setting_key = ? AND status != 'deleted'
`

type GetOrganizationSettingParams struct {
	OrganizationID int64  `json:"organization_id"`
	SettingKey     string `json:"setting_key"`
}

type GetOrganizationSettingRow struct {
	ID             int64                          `json:"id"`
	PublicID       string                         `json:"public_id"`
	OrganizationID int64                          `json:"organization_id"`
	SettingKey     string                         `json:"setting_key"`
	SettingValue   string                         `json:"setting_value"`
	Editable       sql.NullBool                   `json:"editable"`
	Description    sql.NullString                 `json:"description"`
	Status         NullOrganizationSettingsStatus `json:"status"`
	CreatedAt      sql.NullTime                   `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	CreatedBy      sql.NullInt64                  `json:"created_by"`
	UpdatedBy      sql.NullInt64                  `json:"updated_by"`
}

func (q *Queries) GetOrganizationSetting(ctx context.Context, arg GetOrganizationSettingParams) (GetOrganizationSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationSetting, arg.OrganizationID, arg.SettingKey)
	var i GetOrganizationSettingRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getOrganizationSettingByPublicID = `-- name: GetOrganizationSettingByPublicID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, organization_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM organization_settings
WHERE public_id = UUID_TO_BIN(?) AND status != 'deleted'
`

type GetOrganizationSettingByPublicIDRow struct {
	ID             int64                          `json:"id"`
	PublicID       string                         `json:"public_id"`
	OrganizationID int64                          `json:"organization_id"`
	SettingKey     string                         `json:"setting_key"`
	SettingValue   string                         `json:"setting_value"`
	Editable       sql.NullBool                   `json:"editable"`
	Description    sql.NullString                 `json:"description"`
	Status         NullOrganizationSettingsStatus `json:"status"`
	CreatedAt      sql.NullTime                   `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	CreatedBy      sql.NullInt64                  `json:"created_by"`
	UpdatedBy      sql.NullInt64                  `json:"updated_by"`
}

func (q *Queries) GetOrganizationSettingByPublicID(ctx context.Context, publicID string) (GetOrganizationSettingByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationSettingByPublicID, publicID)
	var i GetOrganizationSettingByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProjectSetting = `-- name: GetProjectSetting :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, project_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM project_settings
WHERE project_id = ? AND setting_key = ? AND status != 'deleted'
`

type GetProjectSettingParams struct {
	ProjectID  int64  `json:"project_id"`
	SettingKey string `json:"setting_key"`
}

type GetProjectSettingRow struct {
	ID           int64                     `json:"id"`
	PublicID     string                    `json:"public_id"`
	ProjectID    int64                     `json:"project_id"`
	SettingKey   string                    `json:"setting_key"`
	SettingValue string                    `json:"setting_value"`
	Editable     sql.NullBool              `json:"editable"`
	Description  sql.NullString            `json:"description"`
	Status       NullProjectSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime              `json:"created_at"`
	UpdatedAt    sql.NullTime              `json:"updated_at"`
	CreatedBy    sql.NullInt64             `json:"created_by"`
	UpdatedBy    sql.NullInt64             `json:"updated_by"`
}

func (q *Queries) GetProjectSetting(ctx context.Context, arg GetProjectSettingParams) (GetProjectSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectSetting, arg.ProjectID, arg.SettingKey)
	var i GetProjectSettingRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProjectSettingByPublicID = `-- name: GetProjectSettingByPublicID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, project_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM project_settings
WHERE public_id = UUID_TO_BIN(?) AND status != 'deleted'
`

type GetProjectSettingByPublicIDRow struct {
	ID           int64                     `json:"id"`
	PublicID     string                    `json:"public_id"`
	ProjectID    int64                     `json:"project_id"`
	SettingKey   string                    `json:"setting_key"`
	SettingValue string                    `json:"setting_value"`
	Editable     sql.NullBool              `json:"editable"`
	Description  sql.NullString            `json:"description"`
	Status       NullProjectSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime              `json:"created_at"`
	UpdatedAt    sql.NullTime              `json:"updated_at"`
	CreatedBy    sql.NullInt64             `json:"created_by"`
	UpdatedBy    sql.NullInt64             `json:"updated_by"`
}

func (q *Queries) GetProjectSettingByPublicID(ctx context.Context, publicID string) (GetProjectSettingByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectSettingByPublicID, publicID)
	var i GetProjectSettingByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProjectID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, site_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM site_settings
WHERE site_id = ? AND setting_key = ? AND status != 'deleted'
`

type GetSiteSettingParams struct {
	SiteID     int64  `json:"site_id"`
	SettingKey string `json:"setting_key"`
}

type GetSiteSettingRow struct {
	ID           int64                  `json:"id"`
	PublicID     string                 `json:"public_id"`
	SiteID       int64                  `json:"site_id"`
	SettingKey   string                 `json:"setting_key"`
	SettingValue string                 `json:"setting_value"`
	Editable     sql.NullBool           `json:"editable"`
	Description  sql.NullString         `json:"description"`
	Status       NullSiteSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime           `json:"created_at"`
	UpdatedAt    sql.NullTime           `json:"updated_at"`
	CreatedBy    sql.NullInt64          `json:"created_by"`
	UpdatedBy    sql.NullInt64          `json:"updated_by"`
}

func (q *Queries) GetSiteSetting(ctx context.Context, arg GetSiteSettingParams) (GetSiteSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteSetting, arg.SiteID, arg.SettingKey)
	var i GetSiteSettingRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SiteID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSiteSettingByPublicID = `-- name: GetSiteSettingByPublicID :one
SELECT id, BIN_TO_UUID(public_id) AS public_id, site_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM site_settings
WHERE public_id = UUID_TO_BIN(?) AND status != 'deleted'
`

type GetSiteSettingByPublicIDRow struct {
	ID           int64                  `json:"id"`
	PublicID     string                 `json:"public_id"`
	SiteID       int64                  `json:"site_id"`
	SettingKey   string                 `json:"setting_key"`
	SettingValue string                 `json:"setting_value"`
	Editable     sql.NullBool           `json:"editable"`
	Description  sql.NullString         `json:"description"`
	Status       NullSiteSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime           `json:"created_at"`
	UpdatedAt    sql.NullTime           `json:"updated_at"`
	CreatedBy    sql.NullInt64          `json:"created_by"`
	UpdatedBy    sql.NullInt64          `json:"updated_by"`
}

func (q *Queries) GetSiteSettingByPublicID(ctx context.Context, publicID string) (GetSiteSettingByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettingByPublicID, publicID)
	var i GetSiteSettingByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SiteID,
		&i.SettingKey,
		&i.SettingValue,
		&i.Editable,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listOrganizationSettings = `-- name: ListOrganizationSettings :many
SELECT id, BIN_TO_UUID(public_id) AS public_id, organization_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM organization_settings
WHERE organization_id = ? AND status != 'deleted'
ORDER BY setting_key ASC
LIMIT ? OFFSET ?
`

type ListOrganizationSettingsParams struct {
	OrganizationID int64 `json:"organization_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

type ListOrganizationSettingsRow struct {
	ID             int64                          `json:"id"`
	PublicID       string                         `json:"public_id"`
	OrganizationID int64                          `json:"organization_id"`
	SettingKey     string                         `json:"setting_key"`
	SettingValue   string                         `json:"setting_value"`
	Editable       sql.NullBool                   `json:"editable"`
	Description    sql.NullString                 `json:"description"`
	Status         NullOrganizationSettingsStatus `json:"status"`
	CreatedAt      sql.NullTime                   `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	CreatedBy      sql.NullInt64                  `json:"created_by"`
	UpdatedBy      sql.NullInt64                  `json:"updated_by"`
}

func (q *Queries) ListOrganizationSettings(ctx context.Context, arg ListOrganizationSettingsParams) ([]ListOrganizationSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationSettings, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationSettingsRow{}
	for rows.Next() {
		var i ListOrganizationSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.SettingKey,
			&i.SettingValue,
			&i.Editable,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSettings = `-- name: ListProjectSettings :many
SELECT id, BIN_TO_UUID(public_id) AS public_id, project_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM project_settings
WHERE project_id = ? AND status != 'deleted'
ORDER BY setting_key ASC
LIMIT ? OFFSET ?
`

type ListProjectSettingsParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListProjectSettingsRow struct {
	ID           int64                     `json:"id"`
	PublicID     string                    `json:"public_id"`
	ProjectID    int64                     `json:"project_id"`
	SettingKey   string                    `json:"setting_key"`
	SettingValue string                    `json:"setting_value"`
	Editable     sql.NullBool              `json:"editable"`
	Description  sql.NullString            `json:"description"`
	Status       NullProjectSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime              `json:"created_at"`
	UpdatedAt    sql.NullTime              `json:"updated_at"`
	CreatedBy    sql.NullInt64             `json:"created_by"`
	UpdatedBy    sql.NullInt64             `json:"updated_by"`
}

func (q *Queries) ListProjectSettings(ctx context.Context, arg ListProjectSettingsParams) ([]ListProjectSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSettings, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSettingsRow{}
	for rows.Next() {
		var i ListProjectSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ProjectID,
			&i.SettingKey,
			&i.SettingValue,
			&i.Editable,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettings = `-- name: ListSiteSettings :many
SELECT id, BIN_TO_UUID(public_id) AS public_id, site_id, setting_key, setting_value, editable, description, status, created_at, updated_at, created_by, updated_by
FROM site_settings
WHERE site_id = ? AND status != 'deleted'
ORDER BY setting_key ASC
LIMIT ? OFFSET ?
`

type ListSiteSettingsParams struct {
	SiteID int64 `json:"site_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSiteSettingsRow struct {
	ID           int64                  `json:"id"`
	PublicID     string                 `json:"public_id"`
	SiteID       int64                  `json:"site_id"`
	SettingKey   string                 `json:"setting_key"`
	SettingValue string                 `json:"setting_value"`
	Editable     sql.NullBool           `json:"editable"`
	Description  sql.NullString         `json:"description"`
	Status       NullSiteSettingsStatus `json:"status"`
	CreatedAt    sql.NullTime           `json:"created_at"`
	UpdatedAt    sql.NullTime           `json:"updated_at"`
	CreatedBy    sql.NullInt64          `json:"created_by"`
	UpdatedBy    sql.NullInt64          `json:"updated_by"`
}

func (q *Queries) ListSiteSettings(ctx context.Context, arg ListSiteSettingsParams) ([]ListSiteSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSiteSettings, arg.SiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteSettingsRow{}
	for rows.Next() {
		var i ListSiteSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SiteID,
			&i.SettingKey,
			&i.SettingValue,
			&i.Editable,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSettings = `-- name: ListUserSettings :many

WITH RECURSIVE user_orgs AS (
    SELECT organization_id FROM organization_members WHERE organization_members.account_id = ? AND organization_members.status = 'active'
    UNION DISTINCT
    SELECT r.target_organization_id
    FROM relationships r
    INNER JOIN user_orgs uo ON r.source_organization_id = uo.organization_id
    WHERE r.status = 'approved'
)
SELECT id, public_id, setting_key, setting_value, editable, description, status, created_at, updated_at, parent_type, parent_name, parent_public_id FROM (
    SELECT
        os.id, BIN_TO_UUID(os.public_id) AS public_id, os.setting_key, os.setting_value, os.editable, os.description, os.status, os.created_at, os.updated_at,
        'organization' AS parent_type,
        o.name AS parent_name,
        BIN_TO_UUID(o.public_id) AS parent_public_id
    FROM organization_settings os
    JOIN organizations o ON os.organization_id = o.id
    JOIN user_orgs uo ON o.id = uo.organization_id
    WHERE os.status != 'deleted'

    UNION ALL

    SELECT
        ps.id, BIN_TO_UUID(ps.public_id) AS public_id, ps.setting_key, ps.setting_value, ps.editable, ps.description, ps.status, ps.created_at, ps.updated_at,
        'project' AS parent_type,
        p.name AS parent_name,
        BIN_TO_UUID(p.public_id) AS parent_public_id
    FROM project_settings ps
    JOIN projects p ON ps.project_id = p.id
    LEFT JOIN project_members pm ON p.id = pm.project_id AND pm.account_id = ? AND pm.status = 'active'
    LEFT JOIN user_orgs uo ON p.organization_id = uo.organization_id
    WHERE ps.status != 'deleted'
    AND (pm.id IS NOT NULL OR uo.organization_id IS NOT NULL)

    UNION ALL

    SELECT
        ss.id, BIN_TO_UUID(ss.public_id) AS public_id, ss.setting_key, ss.setting_value, ss.editable, ss.description, ss.status, ss.created_at, ss.updated_at,
        'site' AS parent_type,
        s.name AS parent_name,
        BIN_TO_UUID(s.public_id) AS parent_public_id
    FROM site_settings ss
    JOIN sites s ON ss.site_id = s.id
    JOIN projects p ON s.project_id = p.id
    LEFT JOIN site_members sm ON s.id = sm.site_id AND sm.account_id = ? AND sm.status = 'active'
    LEFT JOIN project_members pm ON p.id = pm.project_id AND pm.account_id = ? AND pm.status = 'active'
    LEFT JOIN user_orgs uo ON p.organization_id = uo.organization_id
    WHERE ss.status != 'deleted'
    AND (sm.id IS NOT NULL OR pm.id IS NOT NULL OR uo.organization_id IS NOT NULL)
) AS all_settings
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUserSettingsParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListUserSettingsRow struct {
	ID             int64                          `json:"id"`
	PublicID       string                         `json:"public_id"`
	SettingKey     string                         `json:"setting_key"`
	SettingValue   string                         `json:"setting_value"`
	Editable       sql.NullBool                   `json:"editable"`
	Description    sql.NullString                 `json:"description"`
	Status         NullOrganizationSettingsStatus `json:"status"`
	CreatedAt      sql.NullTime                   `json:"created_at"`
	UpdatedAt      sql.NullTime                   `json:"updated_at"`
	ParentType     string                         `json:"parent_type"`
	ParentName     string                         `json:"parent_name"`
	ParentPublicID string                         `json:"parent_public_id"`
}

// ============================================================================
// USER SETTINGS (Cross-scope query for dashboard)
// ============================================================================
func (q *Queries) ListUserSettings(ctx context.Context, arg ListUserSettingsParams) ([]ListUserSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSettings,
		arg.AccountID,
		arg.AccountID,
		arg.AccountID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSettingsRow{}
	for rows.Next() {
		var i ListUserSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SettingKey,
			&i.SettingValue,
			&i.Editable,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentType,
			&i.ParentName,
			&i.ParentPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationSetting = `-- name: UpdateOrganizationSetting :exec
UPDATE organization_settings
SET setting_value = ?, updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type UpdateOrganizationSettingParams struct {
	SettingValue string        `json:"setting_value"`
	UpdatedBy    sql.NullInt64 `json:"updated_by"`
	PublicID     string        `json:"public_id"`
}

func (q *Queries) UpdateOrganizationSetting(ctx context.Context, arg UpdateOrganizationSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationSetting, arg.SettingValue, arg.UpdatedBy, arg.PublicID)
	return err
}

const updateProjectSetting = `-- name: UpdateProjectSetting :exec
UPDATE project_settings
SET setting_value = ?, updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type UpdateProjectSettingParams struct {
	SettingValue string        `json:"setting_value"`
	UpdatedBy    sql.NullInt64 `json:"updated_by"`
	PublicID     string        `json:"public_id"`
}

func (q *Queries) UpdateProjectSetting(ctx context.Context, arg UpdateProjectSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectSetting, arg.SettingValue, arg.UpdatedBy, arg.PublicID)
	return err
}

const updateSiteSetting = `-- name: UpdateSiteSetting :exec
UPDATE site_settings
SET setting_value = ?, updated_at = NOW(), updated_by = ?
WHERE public_id = UUID_TO_BIN(?)
`

type UpdateSiteSettingParams struct {
	SettingValue string        `json:"setting_value"`
	UpdatedBy    sql.NullInt64 `json:"updated_by"`
	PublicID     string        `json:"public_id"`
}

func (q *Queries) UpdateSiteSetting(ctx context.Context, arg UpdateSiteSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSetting, arg.SettingValue, arg.UpdatedBy, arg.PublicID)
	return err
}
