// Resource CRUD operations using ConnectRPC

import {
  organizationClient,
  projectClient,
  siteClient,
  firewallClient,
  projectFirewallClient,
  siteFirewallClient,
  memberClient,
  projectMemberClient,
  siteMemberClient,
  organizationSecretClient,
  projectSecretClient,
  siteSecretClient,
  organizationSettingClient,
  projectSettingClient,
  siteSettingClient,
} from "@/api/client";
import { getPageContext } from "@/utils/context";
import { showNotification, capitalize, singularize } from "@/utils/helpers";
import { closeModal } from "@/utils/modal";

// Organization operations
export async function createOrganization(data: { name: string; description?: string }) {
  try {
    const response = await organizationClient.createOrganization({
      folder: {
        name: data.name,
        description: data.description || "",
      },
    });
    showNotification("success", "Organization created successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateOrganization(
  organizationId: string,
  data: { name?: string; description?: string }
) {
  try {
    const response = await organizationClient.updateOrganization({
      organizationId,
      folder: {
        name: data.name || "",
        description: data.description || "",
      },
    });
    showNotification("success", "Organization updated successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteOrganization(organizationId: string) {
  if (!confirm("Are you sure you want to delete this organization?")) {
    return;
  }

  try {
    await organizationClient.deleteOrganization({ organizationId });
    showNotification("success", "Organization deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Project operations
export async function createProject(data: {
  organizationId: string;
  name: string;
  description?: string;
  region?: string;
  zone?: string;
  machine_type?: string;
  disk_size_gb?: string;
  create_branch_sites?: boolean;
}) {
  try {
    const response = await projectClient.createProject({
      organizationId: data.organizationId,
      project: {
        organizationId: data.organizationId,
        projectId: "", // Will be generated by server
        projectName: data.name,
        createBranchSites: data.create_branch_sites || false,
        region: data.region || "",
        zone: data.zone || "",
        machineType: data.machine_type || "",
        diskSizeGb: data.disk_size_gb ? parseInt(data.disk_size_gb) : 20,
      },
    });
    showNotification("success", "Project created successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateProject(
  organizationId: string,
  projectId: string,
  data: { name?: string; description?: string }
) {
  try {
    const response = await projectClient.updateProject({
      organizationId,
      projectId,
      project: {
        name: data.name || "",
        description: data.description || "",
      },
    });
    showNotification("success", "Project updated successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteProject(organizationId: string, projectId: string) {
  if (!confirm("Are you sure you want to delete this project?")) {
    return;
  }

  try {
    await projectClient.deleteProject({ organizationId, projectId });
    showNotification("success", "Project deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Site operations
export async function createSite(data: {
  organizationId: string;
  projectId: string;
  name: string;
  github_repository?: string;
  github_ref?: string;
  compose_path?: string;
  compose_file?: string;
  port?: string;
}) {
  try {
    const response = await siteClient.createSite({
      organizationId: data.organizationId,
      projectId: data.projectId,
      site: {
        siteId: "", // Will be generated by server
        organizationId: data.organizationId,
        projectId: data.projectId,
        siteName: data.name,
        githubRepository: data.github_repository || "",
        githubRef: data.github_ref || "",
        composePath: data.compose_path || "",
        composeFile: data.compose_file || "docker-compose.yml",
        port: data.port ? parseInt(data.port) : 80,
      },
    });
    showNotification("success", "Site created successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateSite(
  siteId: string,
  data: { name?: string; gitRepoUrl?: string }
) {
  try {
    const response = await siteClient.updateSite({
      siteId,
      site: {
        name: data.name || "",
        gitRepoUrl: data.gitRepoUrl || "",
      },
    });
    showNotification("success", "Site updated successfully");
    closeModal();
    window.location.reload();
    return response;
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteSite(siteId: string) {
  if (!confirm("Are you sure you want to delete this site?")) {
    return;
  }

  try {
    await siteClient.deleteSite({ siteId });
    showNotification("success", "Site deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Firewall operations
export async function createFirewallRule(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  ruleType: number;
  cidr: string;
  name: string;
}) {
  try {
    if (data.siteId) {
      const response = await siteFirewallClient.createSiteFirewallRule({
        siteId: data.siteId,
        ruleType: data.ruleType,
        cidr: data.cidr,
        name: data.name,
      });
      showNotification("success", "Firewall rule created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectFirewallClient.createProjectFirewallRule({
        projectId: data.projectId,
        ruleType: data.ruleType,
        cidr: data.cidr,
        name: data.name,
      });
      showNotification("success", "Firewall rule created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await firewallClient.createOrganizationFirewallRule({
        organizationId: data.organizationId,
        ruleType: data.ruleType,
        cidr: data.cidr,
        name: data.name,
      });
      showNotification("success", "Firewall rule created successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteFirewallRule(ruleId: string) {
  if (!confirm("Are you sure you want to delete this firewall rule?")) {
    return;
  }

  const context = getPageContext();

  try {
    if (context.siteId) {
      await siteFirewallClient.deleteSiteFirewallRule({
        siteId: context.siteId,
        ruleId,
      });
    } else if (context.projectId) {
      await projectFirewallClient.deleteProjectFirewallRule({
        projectId: context.projectId,
        ruleId,
      });
    } else if (context.organizationId) {
      await firewallClient.deleteOrganizationFirewallRule({
        organizationId: context.organizationId,
        ruleId,
      });
    }
    showNotification("success", "Firewall rule deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Member operations
export async function createMember(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  accountId: string;
  role: string;
}) {
  try {
    if (data.siteId) {
      const response = await siteMemberClient.createSiteMember({
        siteId: data.siteId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member added successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectMemberClient.createProjectMember({
        projectId: data.projectId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member added successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await memberClient.createOrganizationMember({
        organizationId: data.organizationId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member added successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateMember(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  accountId: string;
  role: string;
}) {
  try {
    if (data.siteId) {
      const response = await siteMemberClient.updateSiteMember({
        siteId: data.siteId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectMemberClient.updateProjectMember({
        projectId: data.projectId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await memberClient.updateOrganizationMember({
        organizationId: data.organizationId,
        accountId: data.accountId,
        role: data.role,
      });
      showNotification("success", "Member updated successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteMember(accountId: string) {
  if (!confirm("Are you sure you want to remove this member?")) {
    return;
  }

  const context = getPageContext();

  try {
    if (context.siteId) {
      await siteMemberClient.deleteSiteMember({
        siteId: context.siteId,
        accountId,
      });
    } else if (context.projectId) {
      await projectMemberClient.deleteProjectMember({
        projectId: context.projectId,
        accountId,
      });
    } else if (context.organizationId) {
      await memberClient.deleteOrganizationMember({
        organizationId: context.organizationId,
        accountId,
      });
    }
    showNotification("success", "Member removed successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Secret operations
export async function createSecret(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  name: string;
  value: string;
}) {
  try {
    if (data.siteId) {
      const response = await siteSecretClient.createSiteSecret({
        siteId: data.siteId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectSecretClient.createProjectSecret({
        projectId: data.projectId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await organizationSecretClient.createOrganizationSecret({
        organizationId: data.organizationId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret created successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateSecret(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  secretId: string;
  name: string;
  value: string;
}) {
  try {
    if (data.siteId) {
      const response = await siteSecretClient.updateSiteSecret({
        siteId: data.siteId,
        secretId: data.secretId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectSecretClient.updateProjectSecret({
        projectId: data.projectId,
        secretId: data.secretId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await organizationSecretClient.updateOrganizationSecret({
        organizationId: data.organizationId,
        secretId: data.secretId,
        name: data.name,
        value: data.value,
      });
      showNotification("success", "Secret updated successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteSecret(secretId: string) {
  if (!confirm("Are you sure you want to delete this secret?")) {
    return;
  }

  const context = getPageContext();

  try {
    if (context.siteId) {
      await siteSecretClient.deleteSiteSecret({
        siteId: context.siteId,
        secretId,
      });
    } else if (context.projectId) {
      await projectSecretClient.deleteProjectSecret({
        projectId: context.projectId,
        secretId,
      });
    } else if (context.organizationId) {
      await organizationSecretClient.deleteOrganizationSecret({
        organizationId: context.organizationId,
        secretId,
      });
    }
    showNotification("success", "Secret deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Setting operations
export async function createSetting(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  key: string;
  value: string;
  description: string;
  editable: boolean;
}) {
  try {
    if (data.siteId) {
      const response = await siteSettingClient.createSiteSetting({
        siteId: data.siteId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectSettingClient.createProjectSetting({
        projectId: data.projectId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting created successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await organizationSettingClient.createOrganizationSetting({
        organizationId: data.organizationId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting created successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function updateSetting(data: {
  organizationId?: string;
  projectId?: string;
  siteId?: string;
  settingId: string;
  key: string;
  value: string;
  description: string;
  editable: boolean;
}) {
  try {
    if (data.siteId) {
      const response = await siteSettingClient.updateSiteSetting({
        siteId: data.siteId,
        settingId: data.settingId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.projectId) {
      const response = await projectSettingClient.updateProjectSetting({
        projectId: data.projectId,
        settingId: data.settingId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting updated successfully");
      closeModal();
      window.location.reload();
      return response;
    } else if (data.organizationId) {
      const response = await organizationSettingClient.updateOrganizationSetting({
        organizationId: data.organizationId,
        settingId: data.settingId,
        key: data.key,
        value: data.value,
        description: data.description,
        editable: data.editable,
      });
      showNotification("success", "Setting updated successfully");
      closeModal();
      window.location.reload();
      return response;
    }
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

export async function deleteSetting(settingId: string) {
  if (!confirm("Are you sure you want to delete this setting?")) {
    return;
  }

  const context = getPageContext();

  try {
    if (context.siteId) {
      await siteSettingClient.deleteSiteSetting({
        siteId: context.siteId,
        settingId,
      });
    } else if (context.projectId) {
      await projectSettingClient.deleteProjectSetting({
        projectId: context.projectId,
        settingId,
      });
    } else if (context.organizationId) {
      await organizationSettingClient.deleteOrganizationSetting({
        organizationId: context.organizationId,
        settingId,
      });
    }
    showNotification("success", "Setting deleted successfully");
    window.location.reload();
  } catch (error) {
    showNotification("error", (error as Error).message);
    throw error;
  }
}

// Generic delete resource function
export async function deleteResource(resourceType: string, resourceId: string) {
  const context = getPageContext();

  switch (singularize(resourceType)) {
    case "organization":
      return deleteOrganization(resourceId);
    case "project":
      if (!context.organizationId) {
        showNotification("error", "Organization ID not found");
        return;
      }
      return deleteProject(context.organizationId, resourceId);
    case "site":
      return deleteSite(resourceId);
    case "firewall":
      return deleteFirewallRule(resourceId);
    case "member":
      return deleteMember(resourceId);
    case "secret":
      return deleteSecret(resourceId);
    case "setting":
      return deleteSetting(resourceId);
    default:
      showNotification("error", `Unknown resource type: ${resourceType}`);
  }
}
