FROM golang:1.25-alpine3.22 AS builder

WORKDIR /build/api
COPY proto/ ./proto/

WORKDIR /build/api/ci/test-runner
COPY ci/test-runner/go.mod ci/test-runner/go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY ci/test-runner/*.go ./

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -ldflags="-s -w" -o /test-runner .


FROM alpine:3.22

RUN apk add --no-cache ca-certificates wget

WORKDIR /app

COPY --from=builder /test-runner /app/test-runner

ENTRYPOINT ["/app/test-runner"]
